### ISSUE TITLE
Translate using an arbitrary chosen language

### ISSUE THREAD

**Issue by JerryBels** [angular-translate/angular-translate#1010]
Hello !

First things first : thanks for this amazing plugin ! It's simply a diamond among regular stones :)

I don't know if I missed something, but if I don't this is according to me missing to the plugin.

I want to use $translate with a translation ID, but don't want to use the currently selected language. Let's say I want to send an automatic message to another user, that doesn't speak the same language as the current user (whose actions triggered the send of the said automatic message). The targeted user's language can be read from the database. Then I want to do something like this : 

    $translate("translation.id", "en")

And if it's available, it uses this, otherwise it uses the fallback language.

Is it doable ?

Thanks !

**Comment by knalli** [comment]
Yeah, you are not the first with that request.

There will be still some work for the spec (your proposed would not work because it is conflicting with the already existing signature).

Perhaps a feature after restructuring the internals a bit.. and/or a contribution by the community. 

Please follow #500
