### ISSUE TITLE
Problem with partialLoader: can translate to incorrect language when addPart() called

### ISSUE THREAD

**Issue by rogercoder** [angular-translate/angular-translate#1032]
Here's a Plunker that demos the issue:  http://plnkr.co/edit/MdXtcg5TUH4lLUDIt2R3?p=preview

The plunker initially shows Phrase1 in Spanish (es). This is correct, because that is the language we are set to `use()`. But once the line adding another part is uncommented, Phrase1 changes to Engilsh (en).

I would think that since the language is set to 'es' that we should get the 'es' translation of PHRASE1.

Is this a bug or am I misunderstanding what `addPart()` is supposed to do?

**Comment by DWand** [comment]
Hello, @rogercoder.

This happens because the partial loader fails loading if it cannot load any of the added parts by default. In your case you did not specified a second part of Spanish translation. So, when you try to add this part the loader can not load it.

But you are free to override this behavior by specifying an error handler to the loader. Just pass a *loadFailureHandler* parameter of the loader. Here is an example: http://plnkr.co/edit/cipFeVPGNvJPQ5DXQn3t?p=preview

We have added information about error handling in the partial loader to our guide with 2.7.0 release. So, if you want, you can find a more detailed explanation [in this chapter](http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading) at the end of a section about the partial loader.
