### ISSUE TITLE
Should localStorage provider use browsers Local Storage?

### ISSUE THREAD

**Issue by jeserkin** [angular-translate/angular-translate#1034]
As far as I've seen, localStorage holds translate in scope, not in browsers Local Storage. Is it a correct behaviour?

Why implement own solution and not use https://github.com/gsklee/ngStorage for storage?

**Comment by DWand** [comment]
Hello, @jeserkin.
Where did you see that?
As far as I know, `$translateLocalStorage` uses browser's local storage, not a simple js scope. See
[master: src/service/storage-local.js](
https://github.com/angular-translate/angular-translate/blob/c343dbf78839f8bd7b21604863d3e80d6d60576d/src/service/storage-local.js)

**Comment by jeserkin** [comment]
According to code it should, yes, but as far as I can tell, when I print window object in console (Chrome), then only language code is present in localStorage. I've specified urlLoader and translates do come in, but I don't see them under localStorage. Are they placed there at some other time?

**Comment by DWand** [comment]
No. The only information `angular-translate` puts in the storage is a language key for now.

**Comment by jeserkin** [comment]
Okay. And where does it hold translates, that are requested with `urlLoader`? At the same time seems a bit odd to say `.useLocalStorage()`. Doesn't seem to be very self explanatory code. I would assume, that translates are plates in Local Storage.

**Comment by DWand** [comment]
It keeps all translations in the internal map. Why should it put them in a storage? The module stores a language key because it has to persist among requests. But translation files may be changed on the server between requests. So, it is not a stable data.

If you want to cache translation files and prevent the module from fetching them each time the page is reloaded, you can use a special method:
```js
$translateProvider.useLoaderCache(true);
```
It is documented in our guide. So, you can find a more detailed explanation in the [Asynchronous Loading chapter](http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading), "Configuration of a loader" and "Using a cache" sections.

As for naming... `.useLocalStorage()` seems to be pretty straight forward. You tell the module which storage to use. But the module decides what information has to be stored on its own.

**Comment by jeserkin** [comment]
Well... So so. But okay. All in all it is good. Now the next question. As far as I've seen this plugin uses it's own storage solution. Why not `ngStorage`?

**Comment by DWand** [comment]
It is not an own storage solution, but rather a light wrapper for a standard feature. It doesn't bring any special abilities or additional dependencies. It doesn't rely on third party components.

`angular-translate` allows you to use any storage you want as long as it implements a desired interface. So, you are free to use `ngStorage` if you want. All you need is to create [a custom storage](https://angular-translate.github.io/docs/#/guide/11_custom-storages).

**Comment by jeserkin** [comment]
I see. Okay.
