### ISSUE TITLE
Is there an option to fetch all translations within a namespace?

### ISSUE THREAD

**Issue by samuelgoldenbaum** [angular-translate/angular-translate#1035]
I'd like to fetch all translations for a namespace in one call like:
```
$translate('page-somepage').then(function (t) {
    $scope.t = t;
});
```
then in my partial:
```    
{{ 't.terms' | translate }} 
{{ 't.privacy' | translate }}
```
right now it seems like I have to specify them each in the controller:
```    
$translate('page-somepage.terms').then(function (terms) {
    $scope.terms = terms;
});
```

**Comment by DWand** [comment]
Hello, @samuelgoldenbaum.

It is impossible to retrieve all translations from a namespace. At least because angular-translate doesn't keep them that way. All nested objects you pass into it are transformed to "plain" objects with nested keys combined with "." symbol. So, `{ns1: {ns2: {key: "translation"}}}` results to `{"ns1.ns2.key": "translation}`.

However, you don't need to use a service to translate things in views. You can translate things directly by either directive or filter:
```html
<div translate="page-somepage.terms"></div>
```

**Comment by samuelgoldenbaum** [comment]
ended up with the following:

In Controller:
````
function mapTranslationsToScope (t, trim) {
        _.forEach(t, function(v, k) {
            k = (trim) ? k.substring(k.lastIndexOf('.') + 1) : k;
           $scope.t[k] = v;
        });
    }

 var translations = [
                "pages.get-started.title",
                "pages.get-started.terms",
                "pages.get-started.subheader",
                "pages.get-started.name",
                "pages.get-started.email",
                "pages.get-started.password"
            ];

$translate(translations).then(function (t) {
    mapTranslationsToScope(t, true);
});
````

In partial
````
        {{ t.terms | translate }}
````

**Comment by DWand** [comment]
You also may be interested in this thing #1021.

**Comment by DWand** [comment]
@samuelgoldenbaum, probably you are doing something wrong. If I understand right, in your example you don't need to use `translate` filter at all because you've already translated all string with the `$translate` service. Have you read our [developers guide](http://angular-translate.github.io/docs/#/guide)? Also, there was a slightly similar question #1022.

**Comment by samuelgoldenbaum** [comment]
Quite right! - I assumed the translations needed to be provided by the controller.
