### ISSUE TITLE
Support default prefix if translation key not found

### ISSUE THREAD

**Issue by pasmuther** [angular-translate/angular-translate#1067]
Supporting default or global keys is essential for large projects when using the concept of sub-keys. It allows to define a fallback to a general key prefix if the sub-key is not defined.

E.g. in case of the missing key "home.subpage1.error" the last sub-key ("error"), shall be prefixed with the userdefined default prefix (e.g. "global") and returns the translation of the key ("global.error"). If this key is also missing, the initial key ("home.subpage1.error") shall be returned.

**Comment by knalli** [comment]
Well, *you* have defined this would be essential. :) But yes: a process of falling back to a standard translation is a common use case.

At the moment, we advice the strategy using one (or multiple) [fallback languages](https://angular-translate.github.io/docs/#/guide/08_fallback-languages) defining the key in question. That's also because we treat the complete translation key as one unit, but not split its parts for individual resolving algorithms.
