### ISSUE TITLE
Messageformat: `count` isnt a number

### ISSUE THREAD

**Issue by pascalmouret** [angular-translate/angular-translate#1118]
Hi, when upgrading to 2.7.2 we've encountered a problem with the type checking when using messageformat interpolation. 

```html 
<span translate="comment-count" translate-value-count="{{ comments.count }}"></span> 
```  

With a translation like this 

 ```messageformat 
{count, plural, one {one comment} other {\# comments}}
 ```  

We get `isnt a number` errors. After a bit of digging it seems that on the first iteration angular-translate tries to interpolate with `{{ comments.count }}` instead of the actual value. Further iterations work fine, it just seems to happen on the first pass. I've downgraded to 2.7.0 for now which seems to fix the problem for the moment.

**Comment by knalli** [comment]
Which version of messageformat.js are you using? Can this difference be an issue of a messageformat.js update? 0.2 vs. 0.3?

**Comment by pascalmouret** [comment]
Sorry for not answering earlier, the notification got lost in my inbox.
Currently bower installs version 0.1.7, so neither of them I'd say :smile:

**Comment by knalli** [comment]
The error is by MessageFormat itself (as the title already said). Also angular-translate does not "know" the MessageFormat internals, we already try to duck check this particular scenario (bbc1cbe).

Can you confirm this situation? It should happen only when the expression (i.e. `comments.count`) will result into undefined/null because not initialized.

**Comment by knalli** [comment]
Closed due inactivity.
