### ISSUE TITLE
Allow to reuse translation keys in combination with other keys and text (properly handle links like @:my.key)

### ISSUE THREAD

**Issue by ixrock** [angular-translate/angular-translate#1132]
Let's consider that we have such localisation strings:

``` json
"some.thing1": "One ({{one}})",
"some.thing2": "Two ({{two}})"
"some.thing3": "@:some.thing1 + @:some.thing2 = 3"
```

I have found already a solution, it require to modify a couple line of code:
https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js

``` javascript
// Lines 1490-1494:
if (translation.substr(0, 2) === '@:') {
    result = determineTranslationInstant(translation.substr(2), interpolateParams, interpolationId);
} else {
    result = Interpolator.interpolate(translation, interpolateParams);
}
```

So, if we replace it to:

``` javascript
if (translation.indexOf('@:') > -1) {
  translation = translation.replace(/@:(\w+(?:\.\w+)*)/g, function (S, translationRefId) {
    return determineTranslationInstant(translationRefId, interpolateParams, interpolationId);
  });
}
result = Interpolator.interpolate(translation, interpolateParams);
```

Afterwards it works, at least I tested it in the form of filter: 
`{{'some.thing3' | translate : ({one: 1, two: 2})}}` gives in output `One (1) + Two (2) = 3`

Can it be released in next version / should I create PR?

**Comment by ixrock** [comment]
Is there anybody alive?

**Comment by knalli** [comment]
Yeah, sorry for the delay.

In a nutshell, just for making the point: You are trying to extend the feature of links from only one to multiple (finite) ones?

Well, you have picked the easiest part applying a patch for the "instant" variant. Much more complex would be the part for the real standard, asynchronous way...

**Comment by joaovieira** [comment]
Any way of getting this behaviour:

```json
{
  "actions": {
    "action": "Action",
    "actions": "@:actions.action + 's'",
    "details" "@:actions.action + ' Details'"
  }
}
```

?

**Comment by akleiber** [comment]
I am interested in an extended link functionality too. Like @joaovieira asked for.
Reusing already defined translation keys would be handy.

**Comment by aszharite** [comment]
any updates on this?

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
