### ISSUE TITLE
useStaticFilesLoader whitelist

### ISSUE THREAD

**Issue by dacox** [angular-translate/angular-translate#1147]
I am currently using `useStaticFilesLoader` to load different translation files.

I currently have this:

```js
$translateProvider.useStaticFilesLoader({
    prefix: "locale_",
    suffix: ".json"
});

$translateProvider.useSanitizeValueStrategy("sanitize");

$translateProvider.preferredLanguage("en-us");

$translateProvider.fallbackLanguage("en-us");
```

So far, this is working great. If we are in a locale that we do not have a file for, the fallback language is selected. However, it would be nice to suppress the 404 error that happens when it tries to load the unsupported locale.

I hoped that registerAvailableLanguageKeys would make it so that it does not try to load any language that is not specified, or whitelisted. However, this does not seem to be the case.

Is there  way to use useStaticFilesLoader in such a way that it only tries to download keys from a whitelist?

Cheers!

**Comment by tspaeth** [comment]
Could you check if https://github.com/angular-translate/angular-translate/issues/920 helps?

**Comment by dacox** [comment]
@tspaeth I don't believe it does. The fallback is actually working just fine for me. if it fails to download a translation table that I don't have, it falls back to english.

What I would like is to have a way of not even trying to download translation tables if I know I don't have them - this will avoid unnecessary HTTP requests.

I thought maybe `registerAvailableLanguageKeys` might help but that doesn't seem to be what it's for.

**Comment by tspaeth** [comment]
@dacox Where do the "wrong" http-requests come from? Do you make a language detection/setting to invalid values upfront? And yes, registerAvailableLanguageKeys could probably help depending on the setup you've made currently.

**Comment by Koblaid** [comment]
registerAvailableLanguageKeys() did work for me to prevent unwanted 404s. Maybe the order of the $translateProvider calls is relevant? I did call registerAvailableLanguageKeys() before everything else.

**Comment by tspaeth** [comment]
@Koblaid Please post your setup as a Plunker or JSfiddle, so we know what and how it is registered. thanks.

**Comment by Koblaid** [comment]
Well, it **does** work for me. Do you want the plunkr as example for @dacox ?

Anyway, I made one: http://plnkr.co/edit/LIHAIirw0MgiwRj9p8PH

It does not try to load any unavailable files. But there is another strange thing: "locale-en.json" seems to be loaded twice. The second loading disappears when I disable line 19 (`$translateProvider.use('en');`). Could be a bug?

In my own code I don't see this effect since the main translation is loaded as angular module. So for me everything is fine.

Hope that helped :)

**Comment by knalli** [comment]
@Koblaid : Yeah, that's a bug when calling `$translateProvider.use()` additional to `preferredLanguage()`. You don't have to. Probably you can avoid this with a loader cache (or `$http` cache).

atm: And it will not likely fixed: We will change the naming and meanings of the terms `preferred language` and `use language` in the next version, because they are producing sometimes confusion. I guess anything we change here will break existing "assumptions".

**Comment by knalli** [comment]
@dacox Your issue is still open?

**Comment by knalli** [comment]
Closed due inactivity.
