### ISSUE TITLE
Unexpected behavior with fallback languages and the translate directive

### ISSUE THREAD

**Issue by proog** [angular-translate/angular-translate#1153]
I'm seeing some strange behavior with fallback languages and the translate directive. I made [a plunker here](http://plnkr.co/edit/yztOrpeAeSC795E3AbeC?p=preview) to demonstrate.

The intention is that there are three languages that each change certain terminology, and the fallback stack is changed during runtime.

It starts out fine, with the pirate language displaying "Ahoy world" (from the sailor language) and "Arrrrr". Clicking the Sailor button replaces the fallback stack and switches to the sailor language. The paragraph is changed accordingly, but the title is not -- instead, it is inexplicably changed to "Hello world", even though the sailor language has a translation for this key. Clicking Sailor again finally changes the title to the correct "Ahoy world".

It seems that using the translate filter instead of the directive fixes the issue. I can reproduce the problem reliably in both Chrome and Firefox. Any idea what's going on here?

**Comment by tspaeth** [comment]
Please try to change the definition order in the change function

```
    $translate.use(lang);
    $scope.fallbacks = $translate.fallbackLanguage(fallbacks);
    $scope.lang = $translate.use();

```

This is one of the things, where we'll have to clean up - it's pending a while, but it'll take a while still... :-|

**Comment by proog** [comment]
Thanks for your reply.

Your suggestion does fix my specific example, but introduces an issue where clicking Sailor and then Pirate changes "Ahoy world" to "Hello world", which it shouldn't.

**Comment by proog** [comment]
So if I understand correctly, this is a known issue?

It seems to me that the options for working around this issue are to avoid changing fallbacks during runtime or use the translate filter instead of the directive.

**Comment by knalli** [comment]
note: We will rework this in the next major version -- at least.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
