### ISSUE TITLE
Promise doesn't fail if translation id from an array is not found

### ISSUE THREAD

**Issue by feimosi** [angular-translate/angular-translate#1222]
Is this an expected behavior that when I translate by id string and it's not found the promise fails, whereas when I use an array as the argument it succeeds and returns the id itself as translation?
This fails:
`$translate('xxxxx')`
This works:
`$translate(['xxxxx'])`
and returns {xxxxx: "xxxxx"} as translation.

**Comment by tspaeth** [comment]
well, it highly also depends on your personal setup. In case of async loaders, the promises won't get rejected with a String input value. Then both will return the key within the success function. If this is right or wrong or intended, I'm not 100% sure... :-) 

@angular-translate/core Did anyone of you still have a historical knowledge how it should always be? Feels a bit minimum inconsistent...

**Comment by feimosi** [comment]
Thanks for the response, so how can I set up angular-translate to be more consistent? 
`"the promises won't get rejected with a String input value"` I'm not sure what do you mean by that. I always pass a string, either alone or in an array, and the first case can fail.

**Comment by knalli** [comment]
Well, IMHO there is no one right way dealing with a failing item when working with a collection of translations.

Two points made the decision not rejecting a collection promise when one item (or more) would be rejectable but not the others:

* optimistic: probably all requested translations are available (eventually loaded)
* usable: if only one missing translation rejects everything, you will not get the chance of getting the working ones.

I know we had similar discussion as we had introduced this feature.

**Comment by feimosi** [comment]
Ok, you're right here. It's not that obvious what to do with collections, but in my case I had only one-element array which should fail, am I right? Also how can I determine which translation failed inside the promise-success callback? I think it'd be better if those not found properties were nulls/undefined inside the returned object.

**Comment by knalli** [comment]
But undefined results would be inconsistent to the "regular" single-request way. Both results relay on the same resolution (in case of a failure).

**Comment by feimosi** [comment]
So basically I cannot determine which translations are missing and which are valid.

**Comment by knalli** [comment]
At the moment, this is not possible. We have decided to implemented the "settled" way (https://github.com/kriskowal/q/wiki/API-Reference#promiseallsettled).

For v3, we will support an additional request method which allows you getting all metadata (i.e. success) for each translation request.

**Comment by feimosi** [comment]
Perfect, thanks for the information.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?

**Comment by feimosi** [comment]
I understand, thanks for letting me know.
