### ISSUE TITLE
Is there a plan to use angular-message-format instead of SlexAxton/messageformat.js?

### ISSUE THREAD

**Issue by vinkaga** [angular-translate/angular-translate#1227]
SlexAxton/messageformat.js has no updates in the last 6 months and its build is failing. Is there a plan to switch to a supported "message format" library like angular-message-format?

**Comment by knalli** [comment]
@vinkaga  Do you have experience with this? Advantages/disadvantages to messageformat.js?

**Comment by vinkaga** [comment]
My main issue with SlexAxton/messageformat.js is that it may not be supported well. No, I don't have any experience with it but it seems to have the same API.

**Comment by dpogue** [comment]
messageformat.js also requires the use of `unsafe-eval` if you're using Content Security Policy

**Comment by knalli** [comment]
I would say we should create a dedicated (new) repository/project for this. Much more safe.

**Comment by eemeli** [comment]
Piping in here as a [messageformat.js](/SlexAxton/messageformat.js) co-author. Its development and support continues actively, as it has over the past few years. The extended pause in production release updates last year was due to slowness in getting our docs updated; that's now happened with [messageformat.github.io](https://messageformat.github.io/).

I noticed that it looks like this project is [using](/angular-translate/bower-angular-translate-interpolation-messageformat/blob/master/bower.json#L11) a version of messageformat.js that's three years old and [209 commits](/SlexAxton/messageformat.js/compare/v0.1.6...v0.3.1) behind our latest release, 0.3.1. We're currently in the middle of another major update (SlexAxton/messageformat.js#138), and it might be a good time to consider updating directly to that; it provides improved multi-language support, better pre-built module output, and easier-to-use custom formatting functionality. This also happens to be a really good time to express any wishes you might have about the library's interfaces.

The `unsafe-eval` use is unfortunately a requirement for how messageformat.js operates when generating translation functions -- the whole point of the tool is to take in an ICU MessageFormat string and output a corresponding JavaScript function. If you'd like to limit that, messageformat.js can be used as a preliminary stage in a build tool, outputting the source code of an AMD/CommonJS/ES6 module of your strings that can then be e.g. stored to disc for inclusion in later compilation stages.

**Comment by knalli** [comment]
@eemeli  Thank you for the update. I'd already raised the version yesterday to 0.3.1 fb48f78 -- will be available in the next 2.11 release. Said that, actually, it is still only a "peer" dependency. Anyone can use another version of messageformat as long as it match the api.

**Comment by eemeli** [comment]
Ah, hadn't noticed that you had a `canary` branch that dropped references to the module with the v0.1.6 dependency.

It looks like the only calls you make to the messageformat.js API are [`$mf = new MessageFormat(lc)`](/angular-translate/angular-translate/blob/8d27947/src/service/messageformat-interpolation.js#L38) and [`$mf.compile(string)`](/angular-translate/angular-translate/blob/8d27947/src/service/messageformat-interpolation.js#L120), and those aren't going to change even with the latest proposed update -- it's only messing with more complex features.

I think I'll also put together a quick PR for a slight change in you messageformat.js output caching; it's a bit sub-optimal atm.

**Comment by knalli** [comment]
Honestly I'm not sure why we had this cache made originally.

Do you even recommend caching the results of `$mf.compile()`? Still best practice (because of "compilation performance")?

**Comment by eemeli** [comment]
Yes, exactly that would be my recommendation, as now made in PR #1432. Essentially, the messageformat.js `.compile()` method is a relatively heavy operation, and the way the library's commonly used, the same compiled function may well get called multiple times. If you have an ability to cache it, you should do so.

**Comment by knalli** [comment]
I'll close this issue. We will stick with messageformat, and not extending our support.

However, we are welcome everyone adding another variant (i.e. angular-message-format). If you find a lack within our api, let us know.

**Comment by danielwegener** [comment]
Which essentially excludes everyone using proper CSP (unsafe-eval somehow defeats its purpose)? Too bad.
