### ISSUE TITLE
Cache issue when using useStaticFilesLoader

### ISSUE THREAD

**Issue by asafse** [angular-translate/angular-translate#1258]
Hi,
I'm using useStaticFilesLoader as part of my support in multiple languages.
I've encountered with an issue that when i'm changing the text value of one of the terms in the JSON file, it does not reflected in my app, only AFTER cleaning the browser's cache.
For example:
        "HEADER": {
            "MY_OPPORTUNITIES": "My Opportunities",
        }

Changed to:
       "HEADER": {
            "MY_OPPORTUNITIES": "My Only Opportunities",
        }

this won't appear in the app only after cleaning the cache.
My deploy process already performs a cache busting using systejs-builder

function bundle() {
  builder = new builder('public/','./config.js');
  builder.buildStatic('app','public/app-' + hash + '.js');
}

How can i handle this use case?
Thanks,
Asaf

**Comment by tspaeth** [comment]
Caching-issues of the browser is usually not an issue of this module but more on your server setup and cache headers in case of external js - files. because, when you reload the app (e.g. F5 on windows etc.), it is completely re-initialized from what you request / cache from the server in terms of data and files.

**Comment by asafse** [comment]
My server side is Rubi On Rails.
I find this issue only with these JSON files while resources such as images, css etc are always being updated - what is the difference?
Is there a best practice to approach this issue?

**Comment by tspaeth** [comment]
Check your network flow and cache headers for retrieval of this files on e.g. the Chrome developer console.

**Comment by knalli** [comment]
Closed due inactivity.

**Comment by charumaheshwari** [comment]
Is there any update on this issue? As this is a valid scenario which is happening. As far as css and js is concerned, caching doesn't happen for them because those files are minified and versioned again. 
Considering above statement, the solution is to do versioning of the json files too? Please confirm

**Comment by knalli** [comment]
This is a closed issue for about 2 years. No updates, see the metadata ;)

You (the app developer) are in charge of serving the resources which includes JSON/translation files also. If you are using a browser cache (which is not a bad idea), you also have to handle revalidations/freshness.

So: If you are changing these files (its content), you must ensure the browser will fetch the newer one. A solution could be a versioning url scheme (either with url rewrite or with a unique param). We as the library author cannot do this for you. We are running JavaScript in the browser only, we do not control your server.

**Comment by FWiner** [comment]
```
var suffix = '.json' + '?t=' + new Date().getTime(); //timeStamp or hashCode
$translateProvider.useStaticFilesLoader({
      prefix: 'lang_',
      suffix: suffix
    });
```
It seems worked for me, and the language json will not be cached.
