### ISSUE TITLE
Load parts in first controller when app start running

### ISSUE THREAD

**Issue by accetone** [angular-translate/angular-translate#1306]
When I tried to load some parts in config and other in controller I faced issue that parts from controller not loaded if this controller invoke when app starts.

Demo:
http://plnkr.co/edit/4GcpIlhPEvxMtyJxRbt1?p=preview

If you uncomment this line
```javascript
$translateProvider.use('en');
```
code is start working, but as you can see in screenshot below part from config loaded two times.

![123](https://cloud.githubusercontent.com/assets/7840570/11283799/7ee4eb78-8f17-11e5-8c83-8edc4a0e23cc.png)

**Comment by tspaeth** [comment]
As this is not the first time someone reports issues here in this "initialization way", I've looked a bit closer:

Hm, I guess the issue lies somewhere in here if the application is not initialized with the $uses variable but only with the $preferredLanguage - in this cases refresh skips the reloading of the parts as $uses is undefined:

https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1873

@knalli what do you think?

**Comment by knalli** [comment]
`$translateProvider.use()` is actually not required when using `$translateProvider.preferredLanguage()` already.

Anyway: There is a `$translate.refresh()` which enforces a reload of all translations. If you call `$translateProvider.use()` explicitly, there will a load of the specified language. Afterwards (in the controller) all languages including the already loaded one will be reloaded. That is actually right because that's the intent of `$translate.refresh()`. 

Perhaps we could add an improvement ("Contributions Welcome") adding something like `$translatePartialLoader.syncronize()`. 

=> This is not a bug, but the result of the given configuration and flow.
