### ISSUE TITLE
Full text instead of IDs

### ISSUE THREAD

**Issue by pocesar** [angular-translate/angular-translate#1329]
My website was using gettext before, and I have all the base text written in Portuguese, and gettext uses `<div translate>Meu texto aqui</div>` which is similar to angular-translate and I thought it would be an easy swap... it seems that angular-translate ignores full text keys and fallback to the text within the DOM. Anyway I can override this behavior, either by a setting or by a `$provider.$delegate`? Even trying to change `1.000 m²` to `1,000 m²` doesn't work

**Comment by knalli** [comment]
@pocesar  Sorry, I don't get this right. What you mean with "full text"?

Given that HTML, the key would be `Meu texto aqui`.. which would be automatically the fallback. What's wrong?

**Comment by tspaeth** [comment]
And on the second part: angular-translate is not a locale-changer. Use $locale for that (e.g. in combination with https://github.com/lgalfaso/angular-dynamic-locale)

**Comment by pocesar** [comment]
@knalli an example directly from my code:

```html
<div class="titulo-sub" translate>Um paraíso em meio a belezas naturais e exclusividade.</div>
```

It won't translate. By full text I mean I'm not using an ID like `BEAUTY_TITLE`

**Comment by tspaeth** [comment]
@pocesar but that's not the approach, angular-translate follows usually... see https://angular-translate.github.io/

What you're "looking for" is what is not-yet finished https://github.com/angular/i18n which is taking better care of "full text" translations I would say...

**Comment by shinrox** [comment]
@pocesar try changing your html to `<div translate>{{ 'Meu texto aqui' }}</div>`

your other lang json keys should be like.

```
//en.json

{
"Meu texto aqui" : "My text here"
}

```

While configuring angular-translate, if you use a language that doesn't have a json, it won't find the key and keep the text passed as interpolation (Portuguese), when switched to en (in this example) it will get the key value.

But this is not a great way to translate things =P, but I think it'll work until you manage to adapt all the text to json. Well, if you're planning to use angular-translate of course.

**Comment by knalli** [comment]
Again: `<div translate>Meu texto aqui</div>` will be picked up by the directive and `Meu texto aqui` will be used looking up used as a translation id. Unless this will be resolved successfully, it will be used as the fallback string. 

Final words on `<div class="metering" translate>1.000.000 m²</div>`: 

1. This is not translation, but localization. We do not add support for this since this is more or less fully covered by AJS itself.
2. Given this example, there is no good translation id (do you want to translate the string `1.000.000 m²`? I don't think so.
