### ISSUE TITLE
Unit testing situation is not bearable

### ISSUE THREAD

**Issue by johannesjo** [angular-translate/angular-translate#1335]
I've to adjust every test because of angular translate? That is not really bearable. Are there any plans to fix this?

**Comment by knalli** [comment]
What do you have to adjust every time?

**Comment by johannesjo** [comment]
You need an additional expectGET for the translations file. You can circumvent this by excluding the module from the tests as I found out, but still, it could be really annoying.

**Comment by knalli** [comment]
Well. If you configure your test with a loader using `$http`, you will properly have to handle there requests.. obviously, that's AngularJS.
However, you do not have to configure a loader or even a loader using `$http`. In most cases, a static translation map will be very sufficient. And in the special edge cases an asynchronous loader is really be required (because of testing other latency/deferred components), a standard loader without `$http` will be sufficient.

Anyway, I don't see the requirement of using a $http loader within tests.

**Comment by knalli** [comment]
Closing this. Question has been answered: Won't fix because there is no bug.

If you include code which relies on XHR, you will have to mock it correctly. That's how AJS unit tests works and this actually not uncommon in other frameworks/languages.

However, an angular-translate setup does not require a XHR loader. It can be totally configured without having one. Of course you have to apply a different setup for tests.. but that should be already the case for mocking other (external) things.
