### ISSUE TITLE
Issue with colon at the end of translation:

### ISSUE THREAD

**Issue by alexrada** [angular-translate/angular-translate#1352]
I'm having this case:

`<label for="regular1" translate>Name:</label>`

Which throws the following error:
`Cannot read property 'substr' of null`

And the JSON file:
`{
    "Home": "Acasa",
    "Name:": "Nume"}`

Using angular-translate with useStaticFilesLoader
Also some translations are not found in the JSON, I'm using nullEmpty

**Comment by alexrada** [comment]
So it seems the error also appears when the translate is not in the JSON file.

**Comment by tspaeth** [comment]
"Name:" might cause problems if you use it as a key. Did you try without?

**Comment by alexrada** [comment]
Yes, it works without the colon.

**Comment by tspaeth** [comment]
I've copied your code with colon now - no problems. What versions of angular and angular-translate are you using?

**Comment by alexrada** [comment]
With colon and with null translation in json file using useStaticFilesLoader.
I think that was the combination that didn't work.

**Comment by tspaeth** [comment]
@alexrada Could you - just to check - provide the angularJS + angular-translate versions you were using in the error case?

**Comment by alexrada** [comment]
So, I'm using angular bootstrap set of directives:

uib-tooltip="{{'This will be the default name for outgoing emails'|translate}}"

and the error
https://docs.angularjs.org/error/$interpolate/interr?p0=%7B%7B%27Email%20addresses%20to%20receive%20notifications%27%7Ctranslate%7D%7D&p1=TypeError:%20Cannot%20read%20property%20%27substr%27%20of%20null

**Comment by alexrada** [comment]
So I have this (angular bootstrap directives)

uib-tooltip="{{'Email addresses to receive notifications'|translate}}">

In language.json this is null
"Email addresses to receive notifications": null

And the error:
https://docs.angularjs.org/error/$interpolate/interr?p0=%7B%7B%27Email%20addresses%20to%20receive%20notifications%27%7Ctranslate%7D%7D&p1=TypeError:%20Cannot%20read%20property%20%27substr%27%20of%20null

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
