### ISSUE TITLE
Translate with translate-attr-* ruins HTML

### ISSUE THREAD

**Issue by artuska** [angular-translate/angular-translate#1356]
Well, here are some simplest cases — http://plnkr.co/edit/TNUzo6DsxyJg2oEuW73g?p=preview — what is wrong with the translations?

UPD. What is going on with my HTML — just look in DevTools — all the `div` and `span` tags are missing inside the `translate` element.

**Comment by knalli** [comment]
Well, it works for me?

The `title` has in all 5 cases the value `Hello`.

Probably your issue is the "missing" scope and the non existing {{number}}? That's right, because the translate directive must be have its own scope. Said this, developers are generally being recommended to use dot notation and the controllerAs syntax. In your case, `controller="MainController as mainCtrl"` and the binding `ng-bind="mainCtrl.number"`. Our directive is only one of many which will make issues like that one.

**Comment by artuska** [comment]
@knalli right click on any of the examples and look in DevTools «Elements» tab — HTML tags are missing — all my `div` and `span` tags are gone! Is it `translate-attr-*` or empty `translate` ruins my HTML or is it Angular?

**Comment by knalli** [comment]
Try out using the latest canary. I think we patched this days ago

**Comment by knalli** [comment]
@artuska Have you tried out the latest canary? Is this version better?

**Comment by artuska** [comment]
@knalli No, I did not tried canary, I've just waited for the 2.8.2 version or something :) Now I see 2.9.0 was released today so this will definetely work.
