### ISSUE TITLE
Function executed for parameter values

### ISSUE THREAD

**Issue by lcarva** [angular-translate/angular-translate#1358]
When using an object for interpolated values, an object's function attribute is executed. Here's the Plunker: http://plnkr.co/edit/VNUP0S?p=preview

This only happens if jQuery is used. This is due to how jQuery implements `.text()` vs Angular's jqLite version. In the jQuery case, `.text()` can take either a string or function. In the case of a function, it'll be executed and the return value is used as the text value. Here's the angular-translate code that triggers the function execution: https://github.com/angular-translate/angular-translate/blob/2.8.1/src/service/sanitization.js#L231

Is this expected behavior?

http://api.jquery.com/text/#text-function

**Comment by knalli** [comment]
@lcarva I don't get the issue, please help me a bit. Do you have security concerns?

**Comment by lcarva** [comment]
If I pass an object to `translate-values` that has a function as an attribute, that function will be invoked. I'm not sure if it's a security concern, but it's unexpected behavior. It's even more problematic, if I'm passing an object that has methods with side effect in it (like making API request).

I easily got around this issue by creating a new strategy that would simply ignore attribute functions. Shouldn't angular-translate do this out of the box?

It's also inconsistent that this only occurs if jQuery is used.

**Comment by knalli** [comment]
Ah, okay. Well, that's actually a feature by AJS, I guess. The object will be passed using the interpolation service by AJS. A function is just a "provider" for an expression.

So, thinking in AJS v1 world, that is actually expected (that's how AJS is working). However, I'm getting your thoughts and concerns. Perhaps it would be good to introduce a `ignoreInterpolationParams(true)`?

**Comment by lcarva** [comment]
Yeah. I think making it configurable might be the best option. It would definitely solve my use case.

**Comment by knalli** [comment]
Well, eventually I would always recommend using values. Providing a `function` is not ideal, too.

**Comment by lcarva** [comment]
It'd be nice if there was a best practices article. I didn't realize earlier that when an object is used as a param and a escape strategy is used, it'll actually escape every attribute recursively. I understand the reason for it, and don't disagree, but it's not obvious at first.

What I end up doing is using a simplified version of the object just for translate:

    <div translate="some.key" translate-values="{ spam: bigObj.spam }"></div>

**Comment by knalli** [comment]
I understand you issue, but we have documented we are using *Angular's interpolation service* [[1](http://angular-translate.github.io/docs/#/guide/06_variable-replacement)]. And that one is documented also [[2](https://code.angularjs.org/1.4.9/docs/api/ng/service/$interpolate)].

**Comment by knalli** [comment]
Said this, we also can add a note in the documentation/guide. Improvements are always welcome. :)

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
