### ISSUE TITLE
translate-cloak directive does not work

### ISSUE THREAD

**Issue by zhenyong** [angular-translate/angular-translate#1369]
see http://plnkr.co/edit/yKJgCwuTgstQGDlLsAvR?p=preview

**Comment by knalli** [comment]
@zhenyong I don't see a problem, it is working in your demo. Perhaps I don't get it right...

1. Please make some effort and make an issue with more details. It is work for you, but it's also additional work for us to figure out what your problem is actually.
2. Thank you for providing at least a working demo, but: This is using an outdated version of angular-translate. Is this intended? Why not using a current one (2.8.1)?
3. You are saying, the cloak is not working. Well, you have defined with the key `TRANSLATION_ID` which is a valid key (=> no persistent cloak). If I change the cloak for the invalid key `TRANSLATION_ID_UNDEF`, the class will stay.
4. Just like with `ng-cloak`, you will have to apply an actual css rule for the `translate-cloak` class hiding the stuff.

**Comment by knalli** [comment]
Linking #1384

**Comment by zhenyong** [comment]
@knalli 
Thank u so much. I misunderstand the purpose of 'translate-cloak' .
