### ISSUE TITLE
Cannot use $filter('translate')('KEY') when using $translatePartialLoader

### ISSUE THREAD

**Issue by maxmantz** [angular-translate/angular-translate#1370]
I have encountered an error when using `$translatePartialLoader` with `$filer('translate')('KEY')`. It seems like the translations don't get properly loaded and the key is displayed instead. When reloading, it displays the correct language but doesn't change back when the language changes.

I have created a [repo](https://github.com/maxmantz/anuglar.translate-Bug-Report) which contains a small demo of the issue.

Is this a problem with $tranlsatePartialLoader or with my usage?

**Comment by tspaeth** [comment]
the translate Filter is not asynchronous while the loaders are. If you need to get translations programmatically, try $translate('KEY').then(function (..... instead.

**Comment by knalli** [comment]
First: Don't use filters in services. Use the appropriate service calls, in case of synchronous translation this would be `$translate.instant()`. However, just as already mentioned: The `instant()` method (and the filter is using this) cannot guarantee the translation are already loaded and available.

Second: In your case, there is no need for using the synchronous way. 

Better way:

```js
  this.switchLanguage = function() {
    vm.currentLanguage = vm.currentLanguage === "de" ? "en" : "de";
    $translate.use(vm.currentLanguage)
      .then(function () {
        // NOW the language is available
        vm.message = $translate.instant("MESSAGE");
      });
  }
```

In this situation you can use `$translate.instant('MESSAGE')` over `$translate('MESSAGE')` because the correct translation is well known *in this specific context situation*.
