### ISSUE TITLE
How to use original string as translationId?

### ISSUE THREAD

**Issue by PaulAnnekov** [angular-translate/angular-translate#1391]
I want to use original string as `translationId`:
```
en.json
{
  'Hello <b>world!</b>': 'Hello <b>world!</b>'
}
```

```
es.json
{
  'Hello <b>world!</b>': '¡Hola <b>Mundo!</b>'
}
```

```
index.html
<div translate>Hello <b>world!</b></div>
```

HTML tags are sanitized when using angular translate in such way. So no bold text... How to make it work right?

**Comment by tspaeth** [comment]
Hi! Have you read through http://angular-translate.github.io/docs/#/guide/19_security ?

**Comment by PaulAnnekov** [comment]
@tspaeth yes. How should it help me? As I understand, default strategy for `2.9.0` is `escapeParameters`. But I don't have parameters and it just sanitizes my string. 

I have found that here https://github.com/angular-translate/angular-translate/blob/c5c20ac7e06d8569c79019b340102ce30fad8572/src/directive/translate.js#L257 I get not `Hello <b>world!</b>` translationId, but sanitized `Hello world!` one. So if I will use 
```
es.json
{
  'Hello world!': '¡Hola <b>Mundo!</b>'
}
```
Everything starts working. I think that directive sanitizes translationId somewhere...

**Comment by tspaeth** [comment]
My personal thinking here is: 
It was never intended to handle complex "keys" with HTML inside - so meaning DOM-structures as keys.

**Comment by knalli** [comment]
`Hello <b>world!</b>` is not a string in the DOM anymore. In order to get a string, we have to transform the result back, i.e. with innerHTML.

Said that, this will not ensure the HTML still looks like the same. Another order of attributes, (empty) attribute values, dynamic attributes, or even browsers' graceful autofixes can change the result.

So it does not make much sense to make more effort allowing this. We highly recommend not to use HTML in the key itself.

**Comment by PaulAnnekov** [comment]
@knalli let's go back to the real life. Nobody uses some complex html inside translations. In 99.99% cases you use:
1. `<b></b>`
2. `<span class=""></span>`
3. `<a href=""></a>`
Adding ability to use html inside translation key will add another format that can be used as translationId - original English string (like in [gettext](https://en.wikipedia.org/wiki/Gettext#Programming)). It's implemented in [angular-gettext](https://angular-gettext.rocketeer.be/) library, but `angular-translate` is more powerful. Changing `text()` to `html()` on this line https://github.com/angular-translate/angular-translate/blob/c5c20ac7e06d8569c79019b340102ce30fad8572/src/directive/translate.js#L159 will make this work.

I propose to make key getter optional. By default it will be `text()`, but you can pass your own function like:
```
function getter(element) {
  return element.html().replace(/\s+/g, " ");
}
```
or even replace `text()` with `html().replace(/\s+/g, " ")`.

BTW, translationId inside `translate` attribute's value supports html: `translate="{{'Hello <b>world!</b>'}}"`, so we can make inner text consistent with attribute's value. I see no problems with this, only more flexible solution.

I can make a PR.

**Comment by knalli** [comment]
@PaulAnnekov I will explain you the real life as a library author. Adding this feature will getting us a lot of issues people complaining that their "translation id" (sic, it should be really an id) is not matching. Because a space is different, because another fancy plugin adds a class or lang attribute, because the browser has changed the order of class attribute values, because it conflicts with another directive value interpolation, ...

We have already some features which are not "bullet proofed" to understand for some people (sigh..). So we will add such things only if  we can ensure it will work always.

> Nobody uses some complex html inside translations. 
Well, you do not see the big picture. You are covering you business case only. Don't make the mistake thinking nobody would ever make it. ;) I've seen here a lot ..

Don't get me wrong: We welcome every PR. In this case, we have to add some corner cases (like mentioned above) in the tests. Even negative ones.

**Comment by tspaeth** [comment]
To assist @knalli: We in the projects use Text - Keys like FOO.BAR.TEXT - no HTML constructs for the translations. HTML-code is surrounding the keys. That's the reason for example, why we didn't go for angular-gettext that time as this was the preferred approach.
The html-full-translation is a good alternative approach - as also angular i18n was planned to be. 
It's nice, but also sometimes more complex to implement as library author and in the projects. 

That's my 2cent...
