### ISSUE TITLE
How do angular-translate and angular-gettext work together?

### ISSUE THREAD

**Issue by philippeluickx** [angular-translate/angular-translate#1448]
### Subject of the issue
I am trying to setup a good workflow for translating my app. Translations go beyond the frontend (we have backend emails and mobile), so I would love to stick to standard approaches e.g. PO files.

https://github.com/angular-translate/angular-translate/issues/177 mentions that both libraries serve different use cases. Could you elaborate a bit?
I would love to generate POT files, not bother about translation IDs,... Then again angular-translate seems to be the way to go (integration to core?).

**Comment by knalli** [comment]
AFAIK gettext+po is used at compile time using grunt-angular-gettext. Perhaps you can combine this build tool and generate on-the-fly JSON files.. which you can use in angular-translate as well. Another option would be https://github.com/angular-translate/grunt-po2json-angular-translate, actually the same purpose.

Both libraries will conflict running in the same angular app namespace (because of conflicting directive/service names).
