### ISSUE TITLE
$translateChangeSuccess not fired after pageload

### ISSUE THREAD

**Issue by Aides359** [angular-translate/angular-translate#1449]
### Problem:

After reloading the page the `$translateChangeSuccess` is not fired on the `$rootScope` (well it actually is but too early)
### Environment:

angular: 1.4.9
angular-transltate: 2.10.0
Google Chrome: 48.0.2564 (seems to be browser independent, also occurred in FF)
### Steps to reproduce

In [this plnkr](http://plnkr.co/edit/w634sKVldJYepYmyor6J) open the console and start the code. Then switch languages using the buttons.
### Expected behaviour

`$translateChangeSuccess` should fire after every translation.
### Actual behaviour

`$translateChangeSuccess` does fire after changing language using the buttons but not after page load.

I've added `console.log()` statements on listener registration, listener fire and event emit in the angular-translate code. When monitoring the console you can clearly see that the first `$translateChangeSuccess` after pageload is fired before the listener in `app.run()` is registered, hence missing the fired event.

**Comment by knalli** [comment]
Hm.. well, that is an interesting thing. I've seen the missing event already, but I had not get into it.

Given your example, I've added the following module:

```diff
+ angular.module('x', [])
+ .run(function($rootScope){
+ 	$rootScope.$on('$translateChangeSuccess', function() {
+   	console.log('Translation completed (before)');
+   });
+ });
+ angular.module('app', ['x', 'pascalprecht.translate'])
- angular.module('app', ['pascalprecht.translate'])
```

If you run this, you will the line `Translation completed (before)`. Just as you already pointed out: It is fired, but too early for (your) application run block. And neither any other controller/directive.

What can we do?

1. The service should perform the loading as soon as possible, so we actually do not want to delay it.
2. You can use `$translate.onReady()`.
3. Even if we define a new emit on our module's run block (with a new internal event name), it will probably be still too early for the other applications. We should play with it, but I'm in doubt it will solve this.

Further ideas anyone? @angular-translate/core

**Comment by KillerCodeMonkey** [comment]
Heyho, ey looked through the source code of angular translate and if i recognize it correctly i found some events are triggered like this:
`$rootScope.$emit` shouldn't it `$rootScope.$broadcast`

Cheers!

**Comment by knalli** [comment]
That should not change the game for this point.

As per definition of both according the official documentation, `$emit()` will fire for each scope upwards starting  the given one (`scope.$parent`), and `$broadcast()` will fire on each child scope downwards starting the given one (~ `child in $scope.$children`). Due serious performance issues of the latter one, we have chosen `$emit()`.

**Comment by KillerCodeMonkey** [comment]
Okay thanks for clearification. Does not know that it triggers for both! :+1:

**Comment by Sayvai** [comment]
angular: 1.4.8
angular-transltate: 2.10.0
Google Chrome: 50.0.2661.75

I get the same issue as @Aides359 also.

In my case, I register the `$translateChangeSuccess` event inside a controller (upon instantiating controller).

So 90% of the time the event does fire after during / after controller instantiated. But roughly 10% of the time I strongly believe the event is emitting before the controller is instantiating (i.e. to register event). So using `$translateChangeSuccess` event is unreliable. I tested this scenario by constantly refreshing the page several times.

Could there be a way to improve the events' reliability?

***
_The reason I register this event inside a controller is because I get untranslated translation key names back from the `$translate()` constructor call inside the promise success handler when only the **fallback** language is adopted after failing to get primary locale via a network request. Hence the decision to use and wait for `translateChangeSuccess` to fire before attempting to get translations using `$translate()`._

**Comment by knalli** [comment]
What is about local $translate.ready() + local event listener translateChangeSuccess?

Perhaps we can create another shortcut handler, however, it would be called for anyone later.

**Comment by Aides359** [comment]
Could you link me the docs of `$translate.ready()`? I can't seem to find it.

While skimming through the docs I found `$translate.onReady(fn)`. Would that help to resolve this problem? If yes, would it be an option to let `$translate.onReady(fn)` fire `$translateChangeSuccess` natively to avoid having to write duplicated code?

**Comment by rcollette** [comment]
I believe the performance issue with $broadcast was resolved quite a while ago.   It doesn't actually "broadcast" in like DOM events.  It's a publish subscriber model so only the actual subscribers are going to be called.

**Comment by Aides359** [comment]
@knalli While doing refactoring I came across this part again. I did try `$translate.onReady()` and it seems to work.
What do you think of the idea to let `$translate.onReady()` fire `$translateChangeSuccess`?
Having to define the same behaviour twice in `.onReady()` and `$translateChangeSuccess` is not really nice for maintainability and kind of violates the concept of least surprise.

**Comment by knalli** [comment]
Well, there is also $translateReady which is actually firing onReady(). The latter is newer and being an easier way of handling the "ready" state.

**Comment by Aides359** [comment]
Maybe describing my current situation will help clarifying my point:

I am using `$translateChangeSuccess` to synchronize language with $locale as proposed in [#276](https://github.com/angular-translate/angular-translate/issues/275#issuecomment-31450621) by @DWand 

```
$rootScope.$on('$translateChangeSuccess', function ()
{
    $tmhDynamicLocale.set($translate.use());
});
```

Since on page load the `$translateChangeSuccess` event is missed I'd have to go for something like this

```function syncLanguage()
{
    $tmhDynamicLocale.set($translate.use());
}
$rootScope.$on('$translateChangeSuccess', syncLanguage);
$rootScope.$on('$translateReady', syncLanguage);```

which would be kind of redundant and counter-intuitive.

As I see it `$translateChangeSuccess` should be fired (as it does) and recognizable (it is missed) after page load so triggering `$translateChangeSuccess` in `$translateReady` seems like a fitting solution.

**Comment by knalli** [comment]
Ready is an one time event, just like jQuery's `$(document).onReady(fn)`. The events can be fired multiple times, depending on their meaning.

If you are looking for a simple once-event "when the translations are ready", you should use `$translate.onReady(fn)`. If this is not working, it could be a bug.

Note: onReady is only some months old.

**Comment by Aides359** [comment]
Not sure if I get my point across... 
What I need is an event that notifies me on any language change (as `$translateChangeSuccess` does), including the very first set language for instance set by `preferredLanguage()`, `determinePreferredLanguage()`, `useLocalStorage()`, ... (which does fire `$translateChangeSuccess` but before `$rootScope.$on('$translateChangeSuccess', ...)` is registered, so the event is missed there.

As far as I can tell it would be a sufficient fix to trigger `$translateChangeSuccess` when `onReady` is called (since `onReady` fires a bit later and the event would be caught correctly).

**Comment by knalli** [comment]
Sorry for the delay.. I don't get it right, still.

Please again, just as simple as possible: Which event in which situation is missing or not "right"? Why is `translateChangeSuccess` wrong?

**Comment by Aides359** [comment]
No worries. 
It's been some time so I can't find the apropriate docs right now but I would expect `translateChangeSuccess` to fire on every language change, even the first one from `nothing -> preferred language` after page load/reload.

This first event is missing however.


After further analysis/debugging it became clear, that the missing event is fired by angular translate, however the event is fired before any event listeners (i.e. set up in `angular.module('app', []).run(..)` are registered, thus the event is never caught and appears to be missing.

**Comment by j3hyde** [comment]
Wanted to add a couple cents to this.  I have the same need:  I need to know when a translation run has completed regardless of whether that is the first one or when the language has been changed later on.

In my testing I find that:
* `$translateChangeStart` is either not fired or is fired before my handler is registered.
* `$translateChangeEnd` and `$translateChangeSuccess` are fired properly however...
* when I use `useMissingTranslationHandler()` to set a handler, that handler is fired _after_ `$translateChangeEnd` and `$translateChangeSuccess` have already fired.

In my application I am trying to summarise the missing translations.  To do this I use a missingTranslationHandler to collect all the translations but need to know when the process is finished.

A simplified plunker is here: http://plnkr.co/edit/GIPS7W3sNgm006kAW5wm?p=preview

Note: a slightly different issue appears to be that `$translateChangeStart` only fires (or only fires late enough) when I use `$translate.use()` within `app.run()`.  Different issue but it displays similar timing problems.

**Comment by knalli** [comment]
Please give 2.14 a try.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?

**Comment by EightArmCode** [comment]
In case anyone finds this thread and still doesn't know what to do - the solution on this SO question worked for me http://stackoverflow.com/questions/41998073/how-to-do-error-handling-for-the-event-translatechangesuccess
