### ISSUE TITLE
HTML escaping does not behave the same if angular-translate is used as directive (instead of as a filter)

### ISSUE THREAD

**Issue by sl3dg3hamm3r** [angular-translate/angular-translate#1458]
### Edit: Possible Dublicate
Sorry, I figured now that this seems to be an ongoing discussion, correct me if I am wrong.

### Subject of the issue
See http://stackoverflow.com/questions/36453261/html-escaping-does-not-behave-the-same-if-angular-translate-is-used-as-directive

### Your environment
* version of angular-translate: 2.8
* version of angular: 1.3.5
* which browser and its version: Chrome, latest version

### Steps to reproduce
```
<p translate="MyKey"></p>
<p translate="{{'MyKey'}}"></p>
<p><translate>MyKey</translate></p>
<p>{{'MyKey' | translate}}</p>
```

Results in:
_Text_          --> italic, why is it not escaped?
_Text_          --> italic, why is it not escaped?
_Text_          --> italic, why is it not escaped?
`<i>Text</i>`   --> I expect it that way

### Expected behaviour
Escaping of HTML should IMHO work the same in both ways (filter or directive).

### Actual behaviour
Escaping of HTML does not work the same.

**Comment by sl3dg3hamm3r** [comment]
P.s.: I could use something like this: `$translateProvider.useSanitizeValueStrategy('escape');`

But this results in:
```
<i>Text</i> --> fine
<i>Text</i> --> fine
<i>Text</i> --> fine
&lt;i&gt;Text&lt;/i&gt; --> Oops, double encoding, not fine
```

Furthermore, this would work neither anymore: `<p ng-bind-html="'MyKey' | translate"></p>`

I basically don't know how to resolve my escape-dilemma, if I want to use translate as directive...

**Comment by knalli** [comment]
I've added an answer to SOF.

In AngularJS applications, the filter's output will be escaped always. This is done automatically and is not under control of the filter function itself. In the opposite, the directive has the complete control about which and how information will be appended/ removed/ and so on.

    // ensure angular-sanitize.js is present
    $translateProvider.useSanitizeValueStrategy('sanitize');

Sanitization is not escaping! Instead of escaping everything, it checks for valid (and secure) string (html, javascript, css). If it is valid, it will use the actual input. Otherwise it will be rejected.

I've made an overview matrix of directive, filter and escape/sanitization settings in angular-translate. The case is an ongoing issue with UTF-8 characters, but I think you will get it: http://plnkr.co/edit/8BHONOjhsxBxxO9oVYOK?p=preview
