### ISSUE TITLE
Q: Link between language

### ISSUE THREAD

**Issue by LukeSkyw** [angular-translate/angular-translate#1462]
### Subject of the issue
I can't make link work between languages.

### Your environment
* version of angular-translate: 2.9.0
* version of angular: 1.5.0
* which browser and its version: Chrome 49.0.2623.110 m

### Steps to reproduce
See this [plunker](http://plnkr.co/edit/XwASOZsF0vLOoEqGEQ1i?p=preview)

I opened a [question](http://stackoverflow.com/questions/36602314/angular-translate-link-not-working) on stackoverflow regarding the aforementioned plunker.
One convincing answer is that you can't make link between languages, but only between different namespaces of the same language.

I wanted a confirmation from you guys because I am skeptical of this explanation. What would be the point of linking two labels in the same language? If you want the same value, just use the same label.
On the other hand, link between languages seems a must. "OK" or "pizza" is written the same way between all languages...

**Comment by tspaeth** [comment]
You can't mix languages.

**Comment by knalli** [comment]
Personally, I would not recommend mixing languages only because some words could be the same.

`OK` is not the same in all languages. Most would accept it, but it would not be natural. :)

And the more technical answer : No, that is not possible. And we are not planing to add such a feature. If you really need this, you have to maintain the language sets on your own and deliver final translation sets.
