### ISSUE TITLE
Warning showing up in production

### ISSUE THREAD

**Issue by aaani** [angular-translate/angular-translate#1477]
I am getting this warning in my browser console even for the minified version of the angular-translate lib `dist/angular-translate.min.js`
```
pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.
```

IMHO error/warnings should be suppressed in production environments.

**Comment by knalli** [comment]
Well, the security concern is so important, we should enforce it actually. But on the other side we do not want to break things (think semver), so this is the only way let the people (developers) to care of and deal with it.

At the moment we have no "production mode"; we only have a minified version which is.. well.. minified source.

I understand your intent opening this issue, but the security aspect is definitely no optional bullet point while configuring angular-translate.

**Comment by aaani** [comment]
I am 100% with you on this. I understand security is super important. But in our use case all the translated strings are static and live in the codebase, and we trust them. 

Also I understand your point - 
> At the moment we have no "production mode"; we only have a minified version which is.. well.. minified source.

Is there anyway this could be added to new/future feature requests?

**Comment by knalli** [comment]
> I am 100% with you on this. I understand security is super important. But in our use case all the translated strings are static and live in the codebase, and we trust them.

Perhaps the message and the document behind the link is not clear enough: it is full okay to trust the messages -- but you *have to* opt-in the old default mode (`null`) manually. Sounds a bit weird, but this is the only way to ensure semver with the little noisy message.

> Is there anyway this could be added to new/future feature requests?

In general: yes. Personally, I have the feeling people will not read the documentation, will only include the minified version and will not care of it. Again: I fully understand your aspect of noisy warnings. But I do not like to reduce effective security (not everyone knows "RTFM" :))  just because of one warning.

**Comment by aaani** [comment]
Thanks for your thoughts. I'll opt-in for the old default mode then. 👍
