### ISSUE TITLE
Get language in .config

### ISSUE THREAD

**Issue by DiV666** [angular-translate/angular-translate#1504]
Hi, great job with angular-translate

Is it possible to get the language in angular.config?

What I want is to set moment.locale in the time remaining angular-language set. Something like that:

```
$translateProvider.useStaticFilesLoader({
    prefix: 'assets/i18n/',
    suffix: '.json'
});
$translateProvider
    .useSanitizeValueStrategy('escaped')
    .registerAvailableLanguageKeys(['es-ES', 'en-GB'], {
        'es': 'es-ES',
        'es_ES': 'es-ES',
        'en': 'en-GB',
        'en_GB': 'en-GB'
    })
    .uniformLanguageTag('bcp47');
$translateProvider
    .preferredLanguage('es-ES')
    .determinePreferredLanguage()
    .useLocalStorage()
    .fallbackLanguage(['es-ES'])
    **.then(function (lang) {
        moment.locale(lang);
    });**
```

I am currently using .run, but does not work well, the event is executed twice or moment not change:
```
angular
    .run(thirdVendorI18n);

thirdVendorI18n.$inject = ['$rootScope'];
function thirdVendorI18n($rootScope) {
    $rootScope.$on('$translateLoadingSuccess', function (e, lang) {
        console.log(lang.language);
        moment.locale(lang.language);
    });
}

CONSOLE LOG =>
> es-ES
> en-GB
```

I need to reload the web after changing language as use some libraries that do not support angular-translate.

Could you help me find the best solution for this?

Thank you very much.

**Comment by knalli** [comment]
Well, even if a language would be "known", it can be switched again because translations are not available for a specific requested language. Therefor you will have to handle the edge cases also.

> I am currently using .run, but does not work well, the event is executed twice or moment not change:

Right. That's exactly what I'm talking about. You will not get rid of this case completely.

At the moment this is not possible, and it would not a full qualified information before all languages have been tried to load.

If you have a situation in which you have this all under control, I would suggest to introduce a "global" default language key (eventually injected/provided by a module).

* You load all languages (incl. moment.js) for your specific default and after translate has fired the event, you will load the final language. In case of final is default, you will probably skip the stop.

**Comment by DiV666** [comment]
Ok, thanks for your response.

I removed fallbackLanguage from config and now is working perfect.

I thought fallbackLanguage does not affect the primary language returns, but I can make do without that option.

Thank you very much.
