### ISSUE TITLE
Prevent translate directive from removing child DOM elements

### ISSUE THREAD

**Issue by beauxjames** [angular-translate/angular-translate#1536]
### Subject of the issue
The problem is that when I need to add a link to an image and all my parameters are localized using angular translate, the image gets the hammer due to the behavior of the translate directive.

```
<a translate translate-attr-href="ANCHOR_URL">
  <img translate translate-attr-src="IMAGE_URL" translate-attr-alt="IMAGE_ALT" />
</a>
```
Note the attempt to provide an image as the content of the link while also having control over the description of the image via the alt tag.

### Your environment
* angular-translate/2.8.1
* angular.js/1.3.15
* browser not applicable

### Steps to reproduce
http://plnkr.co/edit/UraKMdxvQDBVNV6k5hPU

### Expected behaviour
Need to be able to provide attributes to the wrapper element without affecting the child elements within

### Actual behaviour
The translate binding applied to the anchor tag causes the child image to be removed from DOM

**Comment by knalli** [comment]
This is the expected behavior of the translate directive: it will replace the inner content of the element.

At some point, this is really solid technically: We are supporting the syntax `<span translate>TEXT</span>`. And because angular-attr is not a dedicated directive, this is the result.

In your case, you can fix this easily using filters (at the `a`-element).

```html
<a ng-href="{{'ANCHOR_URL' | translate}}">
  <img translate translate-attr-src="IMAGE_URL" translate-attr-alt="IMAGE_ALT" />
</a>
```

**Comment by knalli** [comment]
See also #1027
