### ISSUE TITLE
ng-options in select element not changed upon $translate.use

### ISSUE THREAD

**Issue by cschwaderer** [angular-translate/angular-translate#1542]
In my HTML, I have a 'select`-Element with an 'ng-option` attribute:
`<select ng-options="gender.value as gender.caption for gender in genderOptions">`

Inside the controller, I call `$translate` to translate the options inside `$scope.genderOptions`:

```
$scope.genderOptions= [{value: "male", caption: $translate.instant('MALE')},
                {value: "female", $translate.instant('FEMALE')}];

```

That works pretty well until I change the language via `$translate.use('en');` -- everything on the page changes, but the options in the select element remain the same and or are NOT (as expected) changed to the new language.
Is this a bug or I'm I doing something wrong?

I'm using Angular Translate 2.6.1.

**Comment by knalli** [comment]
Sorry for the delay.

As we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by JedI-O** [comment]
Finally had time to create a small Plunker:
https://plnkr.co/edit/IT2CLQudpBYDZctdVI7z?p=preview
You see: Changing the language from English to Latin changes the text directly put on the put, but doesn't change the ng-options inside the select.

**Comment by giri7io** [comment]
I fixed your plunker,
https://plnkr.co/edit/JeZDNw7HozXhTDIZDjOA?p=preview

As per documentation:
> Returns a translation instantly from the internal state of loaded translation.

I think it translates and returns a string instantly, it's unaware of later changes to translation language

instead you can use 'translate' filter 
hope this helps.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
