### ISSUE TITLE
Module breaks when AMD loader is present but implementation is simple

### ISSUE THREAD

**Issue by KrekkieD** [angular-translate/angular-translate#1563]
### Subject of the issue

The `requireJS` module is present on the page, resulting in a `true` for the check `typeof define === 'function' && define.amd`. The `factory` function is now executed when the module is loaded using `require`. However, the angular app does not use the AMD loader. The presence of the AMD loader on the page is required for other reasons.
### Your environment
- version of angular-translate: 2.11.0
- version of angular: 1.5.9
### Steps to reproduce
- Load `requirejs` or a different AMD loader using a script tag in the `<head>` of the HTML file
- Create an angular module with a dependency on translate and include it in a script tag at the bottom of the `<body>`
- Include the angular translate module using a script tag at the bottom of the `<body>`.
- Alternatively, build the angular sources together into a single javascript file (concat file sources)
### Expected behaviour

The Angular translate module should be properly registered, even though the module is not loaded with the AMD loader.
### Actual behaviour
- The Angular translate module is not registered. 
- An error is thrown due to the fact that the module is not loaded through AMD but in a script tag: `Mismatched anonymous define() module`

**Comment by knalli** [comment]
I don't get it. If you have a truthy `(typeof define === 'function' && define.amd)` expression, it will use this function `define`. What is the problem with that?

The only missing point here: The library does not require AngularJS, therefor you have to configure the dependency to AngularJS in your own (via `shim`).

**Comment by KrekkieD** [comment]
when it uses the `define` I need to `require` the translate file in order for the module to be registered (it runs `factory()` only when the module is required). Since my angular app is not using `require` or any other AMD loader I cannot load the translate module. 

A fix here could be to run `factory()` before the `define([], function () { return factory(); })`, but that still does not fix the error `Mismatched anonymous define() module` which happens when you load the file not via the AMD loader but by using a script tag (since no name is provided in the `define`, i.e. `define('pascalprecht.translate', [], function () { ... })`.

**Comment by knalli** [comment]
Still not get your problem.

https://github.com/angular-translate/bower-angular-translate/blob/2.11.0/angular-translate.js#L7-L19 is not using `require` anywhere; only `define` is being used, but conditionally by the expression already mentioned.

If there is no AMD context (i.e. RequireJS) available, the `define` function will not be invoked. If it is invoked, then you have a AMD context.

Is it possible you have run into [this issue](http://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module)? This would mean you have an AMD context, but load the files without it.

**Comment by knalli** [comment]
`Mismatched anonymous define() module` actually means you have an AMD context. If you don't use it, you should consider not loading it.

**Comment by KrekkieD** [comment]
See these fiddles :)

Good: No requirejs present: https://jsfiddle.net/0vxw61xy/2/
Bad: With requirejs present: https://jsfiddle.net/keoqdhyw/

**Comment by knalli** [comment]
So you are using actually RequireJs, but not using it to load the files (because you have inject them on your own via `<script>`, and this all within an AngularJS application which does not support a real module system?

Well, I got your point. But why you are doing such a stunt? We are using a common UMD header which means you will get this problem with the next library tomorrow again.

Despite this: We can evaluate adding names into the define configuration. This must work in all published angular-* sub modules correctly. And the impact for existing solutions should be as minimum as possible.

**Comment by KrekkieD** [comment]
That's indeed what is happening. The reason it's like this is that it's being used on a corporate website which features angular stuff and legacy non-angular stuff based on AMD modules. Our angular app is using a build process that wraps all files together, the libs itself (i.e. angular, translate) included.

I think adding names into the defines may actually be more complicated than it seems.

Would it not be possible to align with angular or ui-router in terms of implementation? Since angular is kinda weird in terms of module scoping I'm not sure how much actual benefit the AMD wrapper provides. The AMD effect can be achieved by configuring requireJS to load the file as non-AMD source. I do understand that would be a breaking change though. 

Maybe adding an unwrapped version in the dist is easiest?

**Comment by knalli** [comment]
Well, I see your issue. But honestly: Even if we fix this here, you will get this issue in the next library which is using such an UMD header. It is not uncommon. Perhaps it is better you scope your Javascript "mini-apps" into dedicated context scopes instead of attaching everything into one single page context.

> Maybe adding an unwrapped version in the dist is easiest?

Maybe you can make PR adding such files into the build process? Perhaps for `angular-translate.js`: `angular-translate.raw.js`.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
