### ISSUE TITLE
sce sanitization strategy is not secure

### ISSUE THREAD

**Issue by kazinov** [angular-translate/angular-translate#1589]
Hi,

`sce` strategy uses `$sce.trustAsHtml` which does nothing against unsecure html and javascript.

I modified your plunker example added onmouseover='document.write(666);'  to it.
http://plnkr.co/edit/BOvjiLQmHMH7YwFlcLsM?p=preview
And obviously javascript was evaluated using `sce` strategy.
`sanitize` strategy works well.

So why `useSanitizeValueStrategy('sce')` strategy is better that simple `useSanitizeValueStrategy(null)`?

**Comment by knalli** [comment]
Well, it you cannot trust your own translation texts, you will have to use `escape`.

If you can trust your translation texts (so trust them), you probably should always escape the params (because they are unsafe).

If you replace your `document.write` with a less "explosive" `console.log` (and count the different translation texts) as in http://plnkr.co/edit/I44HyUrXg6yPiu63LDWt?p=preview, you will see only the translation texts are being injected.

**Comment by knalli** [comment]
Link #1101

**Comment by knalli** [comment]
`trustAsHtml` can be useful depending the situation of context.

See here for the current overview: http://plnkr.co/edit/rJ0R6GzHGbMVxhSa237C?p=preview
