### ISSUE TITLE
how to show filtered language object in Alert

### ISSUE THREAD

**Issue by OmprakashAmarwal** [angular-translate/angular-translate#1590]
Hello

your code is very helpful for me i used multi language in my mobile application... but i need to convert all alert messages according to change language. please let me know how would i get changed language objects in alert box or toster so that i can show messages.

Thanks

**Comment by knalli** [comment]
Hello,

thank you for contacting us. 

However, we advise you asking common "How to... ?" questions at community boards like [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-translate) because you will reach a bigger audience. Also, providing a complete example (i.e. using this [plnkr template](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview)) might help everybody to find a proper solution faster.

Finally I highly recommend our api documentation and guide available at https://angular-translate.github.io/. Because nothing is perfect, we are welcome any improvements or suggestions found in the docs also provided as a PR.

This issue tracker is mainly for feature and bugs (issues) with the library angular-translate itself. But you're always free to add a feature request later on.

Thanks.
