### ISSUE TITLE
is there a gui editor to simultaneously manage all the dictionnaries .json files ?

### ISSUE THREAD

**Issue by louisdoe** [angular-translate/angular-translate#1604]
Hi

sorry if it's not the best place to ask this !

But is there a gui editor to simultaneously manager all the dictionnaries .json files ?

Thanks !

**Comment by knalli** [comment]
Hello,

thank you for contacting us. 

However, we advise you asking common "How to... ?" questions at community boards like [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-translate) because you will reach a bigger audience. Also, providing a complete example (i.e. using this [plnkr template](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview)) might help everybody to find a proper solution faster.

Finally I highly recommend our api documentation and guide available at https://angular-translate.github.io/. Because nothing is perfect, we are welcome any improvements or suggestions found in the docs also provided as a PR.

This issue tracker is mainly for feature and bugs (issues) with the library angular-translate itself. But you're always free to add a feature request later on.

Thanks.
