### ISSUE TITLE
Using key:object (rather than key:string) in translation file

### ISSUE THREAD

**Issue by Syco54645** [angular-translate/angular-translate#1638]
### Subject of the issue
Using key:object in translation file

### Description
We are using Smartling for our translation service. They allow for us to provide instructions inside of the translation in the format of 
`"FOO": {
	"translation": "Translated Foo",
	"notes": "Limit to a total of 20 characters"
}`
however I am not finding a way to be able to handle this with angular translate. I could write a simple parser but would rather not do that. I was reading up on custom interpolation but since that just passes to $interpolate with no way of knowing if the translation is a string or object it is of little help. Is there some way to handle this?

**Comment by tspaeth** [comment]
Did you check on namespaces? (or do I get the question wrong?)

https://angular-translate.github.io/docs/#/guide/02_getting-started

You can access

FOO.translation
and 
FOO.notes

**Comment by Syco54645** [comment]
> Did you check on namespaces? (or do I get the question wrong?)

This would work but only if we are following that format for everything. Right now we only use that format if we need notes.

**Comment by tspaeth** [comment]
The dot syntax is essential in the project currently. Feel free to provide a concept on how to achieve your suggestion without breaking changes, but I personally currently don't know what the goal is currently. Maybe you could provide a conceptional example / explanation.

**Comment by Syco54645** [comment]
`
"FOO": { "translation": "Translated Foo", "notes": "Limit to a total of 20 characters" },
"BAR": "Translated Bar"
`
Is what I would like to accomplish where there is a way to define the library to always look at the "translation" key for the translation if it exists. Otherwise just use the value provided for the key. I do not see a way to configure this sort of thing. Hopefully I explained that clearly enough to make sense.

**Comment by tspaeth** [comment]
Sorry, I don't get it.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
