### ISSUE TITLE
Hiding Elements With Missing Translation IDs

### ISSUE THREAD

**Issue by mej1d** [angular-translate/angular-translate#1643]
### Subject of the issue
This is probably an unusual use case, but I was wondering if there was a way to completely hide an element if the translation ID is missing.

I looked into `translate-cloak`, but this seems to only hide/show based on whether the translation table has been loaded, correct? I would like the element to remain hidden after the translation table has loaded and the ID is determined missing.

I also looked into `translate-keep-content`, but that feels somewhat hackish because I would have to wrap every element I want to hide.

Any thoughts? Is the best solution creating a custom directive that makes use of the error handling service to add a cloaking class? Would the ng-translate project be interested in this functionality?

### Your environment
* version of angular-translate ^2.12.1
* version of angular 1.5.8
* which browser and its version Chrome 54.0.2840.90

### Steps to reproduce
N/A

### Expected behaviour
When a translation ID is missing, a class similar to `translate-cloak` will persist to hide the element.

### Actual behaviour
The `translate-cloak` class is removed regardless of whether the ID is present. 
I should note that I'm having problems with this class in general and that the `translate-cloak` class is not removed even when the ID is present.

**Comment by tspaeth** [comment]
What I don't get basically: Why does it make sense, to hide elements, if a translation is missing?

**Comment by mehjid** [comment]
We have an app that deploys to different regions with slightly a different version to each region. In general, the difference is only a slight text change to an info box or tooltip. However, each text area requires a full suite of translations and some regions don't require an info box/tooltip at all.

Since the layout and functionality remain otherwise identical, I would really like to drive displaying the info boxes based on whether there is a translation is available at all. It's much easier for us to simply maintain a base json language file and merge additional json files as needed per state than 50 different template files.

**Comment by tspaeth** [comment]
I don't really see this as an issue of the module, but an idea for this special case could be to work with the missingtranslationhandler and do some DOM manipulation inside by looking for the element that needs a visibility toggle based on the key? 

https://angular-translate.github.io/docs/#/guide/17_custom-error-handler

**Comment by knalli** [comment]
This sounds like controlling the app states which is behind our goal: translating. 

In that special case I would recommend controlling states completely outside of translate. If this is really being broken down by querying the translation existence, you could work with the service call promise's rejection or translate-cloak with an explicit translation key payload. 


Grüße
Jan Philipp

**Comment by mehjid** [comment]
I apologize if this is not the correct outlet for this discussion. I did a quick search before posting on where to discuss features and the consensus seemed to be the issue tracker since github doesn't have another built in discussion forum. While my issue is not nearly as ubiquitous, I've seen other feature requests on here and figured, since I'm having the issue, other might as well. It also doesn't seem too outlandish to me since missing IDs are expected in large apps and there is already functionality that manipulates the DOM based on missing translation data (`translate-cloak`).

My problem with using the error handler is that it doesn't seem to provide any reference to the element. I suppose I could set the element ID as the translation ID, but that seems confusing. 

@knalli I think it would make a lot of sense for `translate-cloak` to include this functionality when an explicit ID is provided, but it currently does not. We are actually having issues in general with using `translate-cloak` within transcluded content. Here's a plunker demonstrating both:
http://plnkr.co/edit/agR6WG1qtjRwCWVynCKi?p=preview

Below is our present, quick-and-dirty workaround. I would love feedback for a better approach and would be happy to work on a pull request if anyone had a better idea of how to integrate this into the project. 

```
function TranslateHideDirective($translate, $rootScope) {
    var directive = {
      link: link
    };

    function link(scope, elem, attr) {
      $translate(attr.translate).catch(function() {
        elem.addClass("hidden");

        var removeOnChange = $rootScope.$on('$translateChangeSuccess',
          function() {
            $translate(attr.translate).then(
              function() {
                elem.removeClass("hidden");
              },
              function() {
                elem.addClass("hidden");
              });
          });

        scope.$on("$destroy",
          function() {
            removeOnChange();
          });
      });
    }
```

**Comment by tspaeth** [comment]
If you're looking for a better "how to" - forum - please use Stackoverflow as we only can help with issues and bugs, use: http://stackoverflow.com/questions/tagged/angular-translate 
- you'll reach a bigger audience. 

And yes, it doesn't provide the DOM-element reference directly. In case you only have an element once per page, you can search for it on the DOM and then do the necessary steps.
