### ISSUE TITLE
Publish 1.1.1 to npm

### ISSUE THREAD

**Issue by felixmosh** [angular-translate/angular-translate#1648]
### Subject of the issue
There is any way to publish 1.1.1 version to NPM?

**Comment by knalli** [comment]
Why should we publish this old version?

**Comment by felixmosh** [comment]
Because there are users that uses it... and it available on Bower repo but not in NPM.

**Comment by knalli** [comment]
[1.1.1](https://github.com/angular-translate/angular-translate/releases/tag/1.1.1) is **three years** old right now. This is actually even far away of unsupported.

Technically, we have started publishing to npm with 2.2.1 -- any other version before must be curated. I don't see any effort doing this. If you really have a such old project and are don't want to update (i.e. not touching anything, but why do you want to switch the package manager?).

Said this, I highly recommend updating to a more recent version -- for example the 1.x releases do not have support for newer AngularJS versions.

**Comment by felixmosh** [comment]
Yeah, but i do want to move to new build system that involves Webpack, and without that its a problem.
If it is an easy task for you to publish that version you probably will help not just me.
If not, i will solve it in different way.

**Comment by knalli** [comment]
Well, you will not be happy because that old versions lacking standard npm support (i.e. main/browser which results in not working in webpack out-of-the-box). Said this, it is not an easy drop-in usage. And if we curate this versions, it would be ridiculous not adding all others versions before 2.2 also. Also we do not have one, but a bunch of repositories to care of.

If you are really want to use this old version, you have to use the bower variant or maybe the npm (bower-angular-translate-* repositories) via git and tag. Legacy for legacy.
