### ISSUE TITLE
Is it possible to have the default text as a available language?

### ISSUE THREAD

**Issue by cdloh** [angular-translate/angular-translate#1663]
Is it possible for the default text to be a language option?

Example span I have

`<p translate="translate_value">Here is some content</p>`

If I want that to equal ENG is it possible to mark that as English so that if that is the users preferred language it doesn't do anything, or do I have to keep a seperate English translation file?

If it isn't could this become a feature request?

**Comment by cdloh** [comment]
Note that I have done this by setting the preferred language to a language whos resource doesn't exist but this results in an error in the browser. 

eg

`        $translateProvider.preferredLanguage('XX-NO-LANG')
`

Is there another way to do it?

**Comment by knalli** [comment]
I don't get it right. Can you please explain more or prepare a demo?

**Comment by twwwt** [comment]
If I understand @cdloh right, the question is the following. Consider this paragraph:

```html
<p translate="some_translation_table_key">Here is some content</p>
```

The text within the `<p>` tag is in some language, English in this case. It is furthermore assumed that all texts that appear this way (i.e. that should be translatable) are in the **same** language throughout the entire application. By placing the `translate` directive onto the `<p>` tag, angular-translate should essentially leave the text as it is as long as its current language is set to English. Otherwise, it should take the key `some_translation_table_key`, lookup the translation in the corresponding language table, and **replace** the text by its translation. The point is, that one has to tell angular-translate that the **default** language used by translatable texts appearing directly in HTML is xy (English in this case). The advantage of this approach is that one doesn't need a translation table for the default language since it is implicit in HTML.

**Comment by cdloh** [comment]
Apologies that I wasn't clear but twwt is spot on in this case.

I got around this currently by having a English translation table that had no content / translations in it and disabling fallback so it essentially doesn't translate anything.

**Comment by knalli** [comment]
We don't have such a feature. Although it does make sense using the directive maybe, it opens new questions when using the filter or even the service. 

You can implement a custom error handler which is configured for a specific languageId to return the actual requested translationId: https://angular-translate.github.io/docs/#/guide/17_custom-error-handler
