### ISSUE TITLE
Translated variable replacement

### ISSUE THREAD

**Issue by Aides359** [angular-translate/angular-translate#1667]
Is there any way translate variables inserted into a template string using the translate directive?

Probably an example explains it best:

    // Scope (ng-repeat in real world example)
    scope.index = 4;
    scope.dynamicText = 'earlyBird'

    // Template
    <div translate="header" translate-values-index="{{scope.index}}" 
            translate-value-text="{{scope.dynamicText}}">

    // Translation
    {
        "header": "Advice {index}: {text}", 
                                     ^-- is an translationId and has to be translated when replaced
        "earlyBird": "The early bird catches the worm"
    }

If that does not work, is the preferred alternative to use the filter on the param like this?

    <div translate="header" translate-values-index="{{scope.index}}" 
            translate-value-text="{{scope.dynamicText | translate }}">

**Comment by knalli** [comment]
Using [our directive's feature "Post Compiling"](https://angular-translate.github.io/docs/#/guide/05_using-translate-directive#using-translate-directive_post-compiling) -- if I get you right.

**Comment by Aides359** [comment]
Ah, ok. So you mean something like this?
```
// Template
<div translate="header" translate-values-index="{{scope.index}}" 
        translate-value-text="{{scope.dynamicText}}" translate-compile>

// Translation
{
    "header": "Advice {index}: <span translate='{text}'></span>", 
    "earlyBird": "The early bird catches the worm"
}
```

The html tag in the translation string will probably confuse translators, won't it?

Do you know how this will do performance wise against the filter alternative (extra compile of translated content vs. use of translate filter on passed value)?

**Comment by Red-3** [comment]
@knalli
I have this same question. 
We have found that using angular-translate filters created considerable performance issues in our app - especially in IE11/Edge. So I'm refactoring the app to use the angular-translate directive and avoid using filters and bindings where possible.
 
We already include the translated field name in the (translated) error message using nested filters. The syntax I want to replace is:
```
<small ng-message="required">{{'error.field.required' | translate:{field:('common.myFieldName' | translate)} }}</small>
```

In my bundles (`common_en.json` & `error_en.json`) I have:
`{"common.myFieldName: "Field Name"}`
`{"error.field.required": "{{field}} is required."}`

Expected output when `required` validator is violated:

> Field Name is required.

My first attempt to use the directive. This works (but is inefficient and still relies on using the filter to translate the embedded token): 
```
<div ng-messages="vm.receiptDetailForm.driver.$error">
    <small ng-message="required" translate="error.field.required" translate-value-field="{{'common.myFieldName' | translate}}"></small>
</div>
```

This (which is what I think you're recommending) doesn't:
```
<div ng-messages="vm.receiptDetailForm.driver.$error">
    <small ng-message="required" translate="error.field.required" translate-value-field="common.truckNumber" translate-compile></small>
</div>
```

1) Please could you explain what I'm doing wrong?
2) Please could you improve your documentation of the "Post Compiling" feature and provide an example, because it makes very little sense to me (and I can't get it to work)?

BTW: The link is broken when you click "Improve this doc" on your documentation page - it gives a 404 error.

Thx

**Comment by knalli** [comment]
@Aides359 Ops, overseen. Filter is not an alternative because filter output is escaped always (by AJS). See here http://plnkr.co/edit/rJ0R6GzHGbMVxhSa237C?p=preview (demo because of something else, but last column is filter output)

Hello @Red-3 ,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by Red-3** [comment]
@knalli Thanks for responding quickly.
Here it is:
https://plnkr.co/edit/leGbBcoxsCq7GubOkfEu?p=preview

**Comment by knalli** [comment]
Ah, okay. I get it.

Unfortunately, we don't cover this use case (without using a filter). You can use a translated compilation of a directive also (see here https://plnkr.co/edit/XxIxpRRRteRcCg9soDNX?p=preview), but this relies on a sanitize strategy like `sanitizeParameters` because the text string must not be escaped/sanitized. Have a look at the translation `helloworld`.

If you have the translations (texts) under full control, this is fine. In most cases the parameters are unsafe because they are not under your control (used defined text like username).

**Comment by knalli** [comment]
I think I have answered the actual question here, too.

Everything beyond this use cases is not covered, especially if you want to build a more efficient directive when using combinations with the compilation feature. As the service provides a full api, you can built your own special directive, too.

**Comment by Aides359** [comment]
I could not follow the other problem mentioned here (sadly I currently don't have the time to dig into it deeper) but I think that does answer my the question.

Currently my mentioned approach seems to work just fine, it's just rather ugly to have html inside the translated string.

Would this be a wanted feature or is this out of scope for angular-translate?

**Comment by knalli** [comment]
Out of scope. As I said already: You can build use the service directly also.
