### ISSUE TITLE
Translation or strings in array

### ISSUE THREAD

**Issue by kresogalic8** [angular-translate/angular-translate#1698]
Hey there, I have an array of strings and I want to translate them to Spanish. How can I do that?

```
homeMap = [
            ["From logos and prints, to websites and mobile apps,<br>create anything with Little Pesos."],
            ["What do you need done?"],
            ["Describe your business and its target audience"],
            ["When's this for?"],
            ["Your name: "],
            ["Your email address:"]
        ]
```

**Comment by knalli** [comment]
Hello,

thank you for contacting us.

However, this issue tracker is intended for bugs, tasks, and features for the library angular-translate only.

We highly recommend our api documentation and guide available at https://angular-translate.github.io/. Because nothing is perfect, we are welcome any improvements or suggestions found in the docs also provided as a PR.

Finally, we advise you asking common "How to... ?" questions at community boards like [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-translate) because you will reach a bigger audience. Also, providing a complete example (i.e. using this [plnkr template](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview)) might help everybody to find a proper solution faster.

Thanks.
