### ISSUE TITLE
HTML5 Video Won't Load

### ISSUE THREAD

**Issue by peterwesterlund** [angular-translate/angular-translate#1702]
When having translation on the video source. The video won't load.

`<video controls poster="img/video-posters/{{'view-vid-img' | translate}}"><source src="img/videos/{{'view-vid-nme' | translate}}" type="video/mp4">Video not supported</video>`

angular-translate - v2.9.0
AngularJS v1.6.1
Chrome Version 56.0.2924.87 (64-bit)

**Comment by knalli** [comment]
Well, I suggest the video-implementation will not update on attribute changes. You can track this down and updating the attributes via DOM directly.

In that case, you must defer the template rendering until the translation is available.

**Comment by peterwesterlund** [comment]
Not sure I understand. And I'm not using templates. All the HTML is in one big file. Im using `<div ui-show="activeTab == 2">Tab 2 content</div>` to display the different "pages".

Shouldn't `translate-compile` work? I tried that but didn't work.

**Comment by knalli** [comment]
Well, demo case beats always theory.

Although you are not using an explicit template which will be rendered, your page will be rendered also. That's AngularJS basic stuff.

As I have understand that correctly, you are missing a translated value. So again: Maybe the browser's video-tag implementation will not update changes of these attributes. This can be verified with manually updating it.

**Comment by peterwesterlund** [comment]
Okay so if I wanna manually update it. How do I do that? So that it updates it after translate is loaded.

**Comment by knalli** [comment]
Ehm.. @peterwesterlund : For verifiying the point: Build your video tag, wait for rendering (or use a timeout) and then apply an attribute change via DOM api on your own. No AngularJS required.

**Comment by peterwesterlund** [comment]
But when I apply the attribute change, I need to know what language is chosen so that the right attribute value can be placed. So I need that info from angular-translate.

**Comment by knalli** [comment]
Again: For verifying the point the missing attribute update is not reflected by the browser video-tag-implementation itself, you must update the attribute on your own. No AngularJS required, it is basic DOM API (JavaScript).

If you can verify (again: prepare a demo) that's not the case, we will have a look at again.

Otherwise there will be no way of updating it. Then you have only the option to wrap the video tag into a deferred rendered component/template which will render the tags in question right after a (successful) translation.

**Comment by peterwesterlund** [comment]
Finally, here is a demo: https://plnkr.co/edit/ZZPJL1ReOC0ZOz4VI4kU?p=preview

**Comment by knalli** [comment]
Well, ok. By the way, some notes: That's not a simple test case, because there are a lot of files/libs attached which seems not to be required for this. Besides for demonstrating here, you should always isolate issues to the actual core problem. Minified code also is not helpful.

I'm encourage you making more simple demo cases. I did not mean to make you angry, but this the only way of getting complex and in-app issues into a broader, general and simplified discussion -- e.g. here.

`<source src="http://example.org/{{'view-vid-nme' | translate}}" type="video/mp4">`. 

1. Speaking of angular-translate: It looks like the video url is stored as a translation. Wonder if this is a translation after all.
2. There is a request to the non-interpolated raw string made, because the browser will see this right before AngularJS is being invoked. Because of that common case, AJS has been prepared with `ng-src`. Alternatively, you build a own directive/component which attach a new tag after interpolation or with something like `ng-if`.
3. After removing the csp header, the demo is able to load the external resource video after all (because my Chrome is not complaining any more).
4. And it looks like the video will not be loaded inside the video tag when added with ng-src.

**Comment by knalli** [comment]
That is a simple test case isolating the issue and showing the problem with the DOM API: https://plnkr.co/edit/tBgKYbcXRWNJaNyZxJnF?p=preview

That's the proof it is not an issue with AngularJS (and therefore not with angular-translate): any changes on the `video/source/@src` will be not reflected.

=> Build a dedicated template which ensures the video/source/@src will be filled right from the beginning.

**Comment by knalli** [comment]
And just for reference a poc https://plnkr.co/edit/5qRDFt6w9Xv7trypJZnx?p=preview

**Comment by peterwesterlund** [comment]
I'm sorry but I don't understand a bit what you are talking about. And I'm not sure if you meant your demos should work but they did not work for me anyway.

Anyway I have understand this may be too difficult for me at this stage. I will have to do an ugly solution having the html inside the translate string..

I really wish I understood what you described. But sorry.

**Comment by knalli** [comment]
The first link shows the problem is not angular-translate or AngularJS at all, but that changes on video/source will not be reflected by the browser/implementation of the video tag. That's why isolating test/demo is important. 

The second link is a proof of concept how such a component could look like.
