### ISSUE TITLE
Translate Partial Loader is not loading translation files

### ISSUE THREAD

**Issue by sadiksha** [angular-translate/angular-translate#1710]
I am trying to use translatePartialLoader to translate my app. I have followed the documentation, however I am missing something. When I change the language, the langauge of the page that I have translated using angular interpolation `"{{'TEXT'|translate}}"` is not changed. I am note sure, but I am assuming that the translation partial files are not being loaded.

### My environment
* 2.6.0
* 1.5.8
* Firefox 51.0.1 and chrome 56.0.2924.87 (64-bit)

### Steps to reproduce
I have created a demo app (mvp) in github, you can find it [here](https://github.com/sadiksha/angular-pagination-test). Please clone the project, install browser-sync and start the browser sync in your local development machine to run the project locally. 

### Expected behaviour
Go to https://sadiksha.github.io/angular-pagination-test/ and click on button "EN" the pagination texts "FIRST_TEXT, PREVIOUS_TEXT, NEXT_TEXT, LAST_TEXT" should be translated to "Beginning, Previous, Next and Last".

### Actual behaviour
Nothing happens and the texts are not translated when I click the "EN" button.

**Comment by sadiksha** [comment]
Hi, Can you please have a look at this issue? 
Thank you.

**Comment by knalli** [comment]
Could you please update you environment using much more recent versions?

**Comment by knalli** [comment]
Also,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

You can use your demo case for that, but there can be removed some stuff (like browser sync, minified code).

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by sadiksha** [comment]
Hi,
I have created my own plunker that is very similar to my project and which is the minimum working demo version that I could make. The versions of the angular and angular translate is similar to my project and I want to have the bug reproduced so I used the same environment. 

The normal text are translated where as the texts in the pagination does not get translated. https://plnkr.co/edit/vNT0nQvBAKZb8RnFpjkE?p=preview

**Comment by knalli** [comment]
@sadiksha 

Well, but we do not support such old versions. Before you open requests, you are encouraged to verify the issue with the latest. Also this demo is using different library component versions: 2.6.0 of angular-translate, but latest of partial-loader. I don't know your local setup, but you have to be carefully of selecting versions.

Anyway: I don't see a problem except the buttons. But that's no issue with angular-translate because the filter works (you can verify with a filter in the template). The problem will be the bootstrap components which seems to bind the translation only once (too early).

I encouraged you having a look into the bootstrap documentation about other config options, or general support maybe on StackOverflow.

**Comment by sadiksha** [comment]
Ok @knalli thank you. I will try to create a stackoverflow issue about it. As for this issue, you can close it. Thank you.
