### ISSUE TITLE
Static File Loader not using the cache

### ISSUE THREAD

**Issue by jkrot** [angular-translate/angular-translate#1716]
I have loaded a cached response into $translationCache and when that file is called with $translateProvider.useStaticFilesLoader it doesn't load the file from the cache.  

"angular-translate": "2.15.1",
"angular": "1.5.11",
Chrome Version 56.0.2924.87 (64-bit)

### Steps to reproduce
I can't get the useStaticFilesLoader to work in plunker.  Here is my appConfig and appRun Calls for these template cache.

```
function appConfig ($translateProvider) {
    'use strict';

    $translateProvider.useStaticFilesLoader({
        prefix: 'script/locale-',// path to translations files
        suffix: '.json'// suffix, currently- extension of the translations
    });
    $translateProvider.preferredLanguage('en_US');// is applied on first load
    $translateProvider.useSanitizeValueStrategy('sanitize');
    $translateProvider.useLoaderCache('$translationCache');
}
```

```
function appRun ($translationCache, $templateCache) {

    var cacheObj = [200, $templateCache.get('script/locale-en_US.json'), {}, "OK"];
   // When I console log the object is gets the correct file back from template cache.
    $translationCache.put('/script/locale-en_US.json', cacheObj); 
 // When I console log a get from this object after putting it returns the result I expected. 
}
```

When $translateProvider.useStaticFilesLoader calls the file I believe it should be using the template cache to pull the file instead of trying to load it locally.  
I have tried several variants of     
$translateProvider.useLoaderCache(true);
$translateProvider.useLoaderCache();

None of the calls use the cache to resolve the call.

**Comment by jkrot** [comment]
I see the problem here, I expected the static file call to check the $translationCache before trying to make the $http call similar to what $templateCache does however that isn't what is happening.  I am not sure if this is really a bug or lack of documentation for $templateCache.

**Comment by knalli** [comment]
Hm, actually, we are only configuring the existing caching option of AJS. Unless we have configured something wrong (and your 2nd post), I don't see an issue within angular-translate... do you?

Or: I didn't get it yet.

**Comment by jkrot** [comment]
If the translations were in the cache, the http call failed but the translations didn't show even though they were in the cache already.  The app can basically run without internet if needed but checks for updated translations.

**Comment by knalli** [comment]
Well, if the request is made the cache has not being used, I would guess.

If the cache is not used by angular-translate, we must have a look into it (because that's a bug). And if the request is made, a negative response will probably purge the cache content (actually, quite reasonable).

I can see in your case, that you are looking for a more "offline variant" of this. So maybe a custom loader in combination with a manifest or web worker is the thing you want.

**Comment by jkrot** [comment]
From what I can tell the latter case is happening,  the cache is being purged due to the 404 response.  I had to work around this with a custom loader but wasn't something I was expecting.   Maybe an option for future configs for cache not to purge based on a failed load.

**Comment by knalli** [comment]
Again: We are relaying on the [AngularJS $http.cache](https://docs.angularjs.org/api/ng/service/$http). If this not working as expected for you, I would recommend a wrapper cache loader. Actually, such a loader is a very simple function only. Said that, you are able to provide such an improved caching algorithm.

Because we do not want to add this into the "core" also, maybe you want to publish this separately. Then we can add a link to this extra addon.
