### ISSUE TITLE
Use .text() instead of .append() for default translation

### ISSUE THREAD

**Issue by malaupa** [angular-translate/angular-translate#1717]
### Use text instead of append for default translation
In https://github.com/angular-translate/angular-translate/blob/master/src/directive/translate.js#L291 is used `.append()` instead of `.text()` This prevents escaping of <> and other special characters. We use translate directive in mixed cases. The interpolated value could be a translation key or a normal string which is binded to the controller or scope.

### Your environment
* 2.12.1 of angular-translate
* 1.5.8 of angular
* chrome latest

### Steps to reproduce
https://plnkr.co/edit/AmfWUn75kEtvVZcrbFN9?p=preview

### Expected behaviour
Escaping should be happen.

### Actual behaviour
Escaping is not active.

**Comment by knalli** [comment]
Hi, please have a look at our guide, in chapter [Security](https://angular-translate.github.io/docs/#/guide/19_security).

An overview of the modes is available at http://plnkr.co/edit/rJ0R6GzHGbMVxhSa237C?p=preview 

We have some [open discussion in general about this topic](https://github.com/angular-translate/angular-translate/labels/ref%3Asanitization).

I'll close this issue, because we will not replace it. Otherwise we could never support unescaped content.

**Comment by malaupa** [comment]
This issue is not about the content. It is about the key which is used to determine a translation. We use HTMl content as well, but for the default translation case, which is, not to find any content for the key, should be escaping like a normal `{{ctrl.binding}}`-binding does.

**Comment by knalli** [comment]
Actually, this is content. And you are pointing to the content's injection part.

{{ctrl.binding}} is an implicit filter binding and will be escaped always (see also my last link). Again: We have different modes to support.

We strongly recommend to use IDs as translation keys which is meant without HTML or other structure code. Otherwise I cannot follow you..

**Comment by malaupa** [comment]
OK, thank you for the clarification. I will use the a factory for `useMissingTranslationHandler` to escape keys.
