### ISSUE TITLE
useSanitizeValueStrategy('escape') on Directive fails with interpolated content

### ISSUE THREAD

**Issue by jimmykane** [angular-translate/angular-translate#1722]
### Subject of the issue
Hi there, 
using angular-transalte as a directive for example: 

```
<td translate="{{ app.unsecureContent }}"></td>
```

Fails to properly escape the content in any strategy provided for useSanitizeValueStrategy

I have edited the plunker provided by you to reflect my problem. Please refer to last strategy.

Plunkr: http://plnkr.co/edit/lSxTJAVpirKc3MEG4bUx?p=preview

Is this due to something I am missing here? 

### Your environment
* version of angular-translate -> Latest
* version of angular -> 1.3.20
* which browser and its version --

### Steps to reproduce
Plunkr: http://plnkr.co/edit/lSxTJAVpirKc3MEG4bUx?p=preview

**Comment by knalli** [comment]
I don't get it..?

**Comment by jimmykane** [comment]
@knalli Using the 'escape' strategy the escaping does not really work. 
In the above plunkr provided you can see that still, the text is bold. 

Here is a screenshot: 

<img width="832" alt="screen shot 2017-04-20 at 19 08 59" src="https://cloud.githubusercontent.com/assets/1268723/25243322/e78a16e4-25fc-11e7-8383-4073e8413fa3.png">

As you can see I edited the code, keeping the strategy and still this is not escaped. 

Maybe it's me not understanding this correct. 

Let me explain: 

I recently started working on a project that we use angular translate. We got a security audit and the security audit revealed tons of issues related to angular translate (latest version). 

We configure angular translate to use SanitizeStrategy of 'escape', but when using it as an attribute, the content is not escaped. 

So for example if in a controller I do this: 

```
$scope.unsafe = '<script>alert(1)</script>'; 
```

and I have an element that needs to get this unsafe var translated like so: 

```
<td translate="{{ unsafe }}"></td>
```

The alert still shows. 

What do you think?

**Comment by knalli** [comment]
Let's say for reference (writing less here)

```
$UNSAFE=`<td translate="{{ unsafe }}"></td>`
```

* The AngularJS (filter) expression `{{$UNSAFE}}` will evaluate this to the `translationId == $UNSAFE`. This will be the same as calling `$translate.instant($UNSAFE)` respectively `$translate($UNSAFE);`
* angular-translate will try to resolve a translation, but this will fail probably
* because of the fail, the id will be used *as-is* (because escaping or something else is part of the translation process)

There are two things to say:
1. You can intercept yourself and change the behavior of the "failing text": https://angular-translate.github.io/docs/#/guide/17_custom-error-handler, maybe add escaping on your own.
2. Maybe it is not clear enough, but the doc says the translator can return the requested translation id. 

Despite the name, we strongly recommend to use the pattern/idea of "ids". 

Obviously, sometimes there is need for building the translation id because of too dynamic use cases. But you have to know your bad user data; simply don't trust the user (input). If your app uses poisoned user input data for building a translationId, you have already a big problem. Fixing this one here with a general escape of the error is only fixing the symptom. The underlaying root problem (handling unknown/invalid/user input data) would be still unhandled.

On the other side, this default is being unsecure at default right now. I think we can go with escaping translation ids on error only.

You are welcome to provide a PR for adding such a feature: 
* Starting point would be i.e. [this](https://github.com/angular-translate/angular-translate/blob/dc68a40dd1b7d49a8deca5344d4c5451982b7538/src/directive/translate.js#L273), but there are some other directives' usages of error handlings.
* It would be good if we provide an optional opt-out like `$translateProvider.enableDirectiveEscapingOnError(false)` (like [this](https://github.com/angular-translate/angular-translate/blob/dc68a40dd1b7d49a8deca5344d4c5451982b7538/src/service/translate.js#L755-L758))
* Alternatively in the directives, a more solid variant would be in the service itself (see [here](https://github.com/angular-translate/angular-translate/blob/dc68a40dd1b7d49a8deca5344d4c5451982b7538/src/service/translate.js), search for `.reject(apply`) -- unfortunately there is no context available which means filter/service call would be return escaped ids also.

**Comment by jimmykane** [comment]
Thanks a lot @knalli 
I was suspecting the same on why it fails to escape, but I have to admit it was not self-implied, when adding the strategy, or in the docs, thus the confusion on my side. 

Regarding user input, a lot of times you have already saved user input and other times it is for convenience, for example when you supply translations via 3rd party. You cannot trust completely the 3rd party. It's a possible attack vector as you see in this case. 

I am going to take a look to see if I am capable of sending a PR and notifying you accordingly. 

Thanks again for your time and your effort.

**Comment by jimmykane** [comment]
@knalli Fixed most of the issues on production. Hopefully tomorrow I can start with the PR.

**Comment by jimmykane** [comment]
@knalli I have made some progress on this. 
I see that most of not found translation go through the `applyNotFoundIndicators`. 
That prepends and appends the missing indications if they are set. 

I am though in doubt if the 'escaping' should happen if there are indicators or if there are not indicators. 

I can understand that this feature is used to detect the missing translations for example: 

```
++TRANSLATION_ID++
```
Escaping the translation id might cause some unwanted behaviour. 

On the other hand, I can escape it only if there are no indicators, which I presume is the case on development setups, and that will not change the current state that users expect, but still, that content might cause an issue. 

What do you think?

**Comment by jimmykane** [comment]
I will provide a cleaner method fixing an inconsistency that was found in #1314 as well

**Comment by jimmykane** [comment]
How about this: 

https://github.com/angular-translate/angular-translate/compare/master...jimmykane:feature/interpolate_not_found_translation_ids

**Comment by jimmykane** [comment]
Any update on this ?

**Comment by jimmykane** [comment]
Ping

**Comment by knalli** [comment]
Oops.. missed this one. Will have a look soon.

**Comment by knalli** [comment]
Ok, please start as PR, better to comment on the code.

1. The doc for interpolateNotFoundTranslationId is wrong about the default value.
2. Without executing the code, it does looks good. 
3. Please add at least 3 tests (default, enabled, disabled).

**Comment by knalli** [comment]
Despite the remarks, it looks great. Well done! 👍

**Comment by jimmykane** [comment]
@knalli  Will do sir! Need some time

**Comment by knalli** [comment]
Hello,

I'm closing this issue due inactivity. We have asked for additional details, but you could not helped us. Therefore we close this issue as not reproducible.

If you still have an issue, please create a new issue because we cannot be sure to track closed issues.
