### ISSUE TITLE
change param search char

### ISSUE THREAD

**Issue by Darkein** [angular-translate/angular-translate#1732]
### Subject of the issue
Hello,

I have to share my translations in both front and back app code, it was easy until i need to insert params in my translations. My server translations look like this '`my name is {0}`'.
At first i was thinking about create a filter whose parse my translation into the good format, but i wonder if there was a more elegant way (like creating a custom translateInterpolation or easier: configure the delimiters chars)

Thanks!

**Comment by knalli** [comment]
Hello,

thank you for contacting us.

Short answer: You can built your own custom loader which also can read/transform any data you want.

However, we advise you asking common "How to... ?" questions at community boards like [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-translate) because you will reach a bigger audience. Also, providing a complete example (i.e. using this [plnkr template](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview)) might help everybody to find a proper solution faster.

Finally I highly recommend our api documentation and guide available at https://angular-translate.github.io/. Because nothing is perfect, we are welcome any improvements or suggestions found in the docs also provided as a PR.

This issue tracker is mainly for feature and bugs (issues) with the library angular-translate itself. But you're always free to add a feature request later on.

Thanks.

**Comment by Darkein** [comment]
Hi,

thanks for your answer.
I'm sorry, because i needed a fast solution i spoke about how i could do it.
But the feature should be "make the delimiter chars customizables".

Do you want me to create a "proper" new feature?

**Comment by knalli** [comment]
You are right: You can yourself create a custom interpolation, then you have this under you control.
