### ISSUE TITLE
How to show Loading GIF when Async download loading literal / locale file?

### ISSUE THREAD

**Issue by hani647** [angular-translate/angular-translate#1741]
First of all guys Thumbs Up to your contribution (y)
Currently I'm using your service in my major project but I'm stuck at a point that when I use $translate.use() it downloads new literal files i.e. other language file and it works fine but I want to show Loading GIF till new language literal file is not fully downloaded. Any help would be appreciated, Thanks

**Comment by thfeng** [comment]
I am facing the same problem. my template was loaded before translate service to load the language file.

**Comment by knalli** [comment]
I'm not sure: if you want to intercept events for loading start and loading finish, you can listen for the corresponding events (see docs). Otherwise you can also implement an own custom loader which maybe delegates to an actual one.

That's it?

**Comment by hani647** [comment]
Can you please send me document link please? :) I appreciate your help

**Comment by knalli** [comment]
Go to the project page here on GitHub, and click either on the top link or the documentation in the readme.

**Comment by hani647** [comment]
I'm using static file loader but problem is that my file is 120KB large so that if someone changes language then it takes 10 to 15 secs to download that file for that time user is not aware what is going on so to update user I need a GIF loader so that I'm using $translate.use() function to load my JSON file now I want that when I call $translate.use() then a GIF loader will be initialized which will last till entire file is downloaded. Can you please share a snippet if possible? I appreciate your help, Thank !

**Comment by knalli** [comment]
Again: use the documentation and have a look for our events publishing loading states or the section about custom loaders.

I'm closing this issue because it is neither a bug nor a feature for angular-translate. You are looking for custom solution, and this is not the right place for this.

----

This issue tracker is intended for bugs, tasks, and features for the library angular-translate only.

We highly recommend our api documentation and guide available at https://angular-translate.github.io/. Because nothing is perfect, we are welcome any improvements or suggestions found in the docs also provided as a PR.

Finally, we advise you asking common "How to... ?" questions at community boards like [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-translate) because you will reach a bigger audience. Also, providing a complete example (i.e. using this [plnkr template](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview)) might help everybody to find a proper solution faster.

Thanks.

**Comment by hani647** [comment]
Wait Wait Wait... Its not a bug? Really? My entire webpage is rendered but JSON file is still loading... Isn't a major bug? please buddy if you don't want to help? so no problem but please don't be upset.. Cheer Up ;)

**Comment by knalli** [comment]
Maybe you got it wrong: I'm not upset. Only referencing to existing stuff here (see [here](https://github.com/angular-translate/angular-translate#get-support), but also [angular-translate.github.io](https://angular-translate.github.io/)).

Due limit resources we are handling mainly bugs (incl. doc) at this level here. Features can be requested, but will be more likely rejected (because we *are* already support a lot of and most feature requests are either high level solutions based on existing ones or are very special custom features).

**Comment by hani647** [comment]
Ok no problem I understand. Thanks For Your Quick response 👍
