### ISSUE TITLE
Translate filter does not work on a dynamically loaded HTML content

### ISSUE THREAD

**Issue by felixkoder** [angular-translate/angular-translate#1755]
### Translate filter does not work on a dynamically loaded HTML content
Hi, I'm trying to use the translate filter on a dynamically loaded HTML but the HTML never changes to the proper translation instead of show the translation I get  the declaration: `{{ 'HEADLINE' | translate }}` when I put all the HTML in the same file it works perfectly. There is any way to achieve that without using the translate service in the controller? I'm requesting the HTML content using an AJAX request, then I set the content into a DOM element:
`$$.get('profile.html', function (data) {
                $$('#profile').html(data);
            })`

There is any way to let angular-translate filter known that there is a new content that need to be translated? 

### Your environment
* version of angular-translate: 2.15.1
* version of angular: 1.5.7
* which browser and its version: Chrome 58

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Also note: Maybe you are using non-angularjs APIs, so you should be aware of applying an additional scope digest?

**Comment by Ssabin-devalore** [comment]
https://plnkr.co/edit/TaUcRyTNlGpl1yZuQieo?p=preview 
Change the language and the template string will load into div.
Though i don't use angular-sanitize.js and i cant upgrade the versions in my project

**Comment by knalli** [comment]
If you add (HTML) fragments on your own into DOM, you have to compile the template on your own. That's an AngularJS base issue, not related to angular-translate.

However, I would recommend to use an AngularJS directive + template, that's is much easier.

**Comment by knalli** [comment]
Hello,

thank you for contacting us.

However, this issue tracker is intended for bugs, tasks, and features for the library angular-translate only.

We highly recommend our api documentation and guide available at https://angular-translate.github.io/. Because nothing is perfect, we are welcome any improvements or suggestions found in the docs also provided as a PR.

Finally, we advise you asking common "How to... ?" questions at community boards like [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-translate) because you will reach a bigger audience. Also, providing a complete example (i.e. using this [plnkr template](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview)) might help everybody to find a proper solution faster.

Thanks.
