### ISSUE TITLE
Angular-translate (Pascalprecht) $translate service is not returning a promise

### ISSUE THREAD

**Issue by robertochingon** [angular-translate/angular-translate#1782]
Hi,

  please see the description here: 
https://stackoverflow.com/questions/46455794/angular-translate-pascalprecht-translate-service-is-not-returning-a-promise
and trying to fix it I tried to upgrade and got next issue: 
https://stackoverflow.com/questions/46457065/upgrading-to-angular-translate-pascalprecht-v2-15-2-and-angular-1-0-7

### Your environment
* version of angular-translate: 1.1.0
* version of angular: 1.0.7
* which browser and its version: Google Chrome Versión 61.0.3163.100

**Comment by knalli** [comment]
AngularJS 1.0 is too old and out of support since years.

**Comment by knalli** [comment]
We are running tests and cover the old 1.2 still. But honestly, get the latest one. Or stick with the old lib. We do not support this.

**Comment by robertochingon** [comment]
This is the title of the github project: Translating your AngularJS 1.x apps. So, supposely it should work on angular1.0.7, right?

**Comment by knalli** [comment]
Well, we have documented the compatibility both in the readme as well as in the package descriptors (bower.json, package.json). If you ignore these, well,you cannot complain.

**Comment by robertochingon** [comment]
Ok, I have checked compatibilities. Let´s try in another way. Could you please confirm which version of angular-translate resolves the service $translate as a promise (so .then can be used in the service). Is not clear to me which version is supporting this functionality reading the logs.

**Comment by knalli** [comment]
Sorry, but it has taken some more days as expected. 

My full answer to the topic of old frameworks/deprecation notices and any future requests this related.

1. Although we are claiming "Translating your AngularJS 1.x apps", you have to check the actual compatibility and especially the version matches between your local environment and the available packages. For example, we are providing information the current release is still working with AngularJS 1.2. Maybe it works in older ones, but will do not run tests against it and therefor do not support it. 
The claim is required for everyone to be sure no one is using our framework with **Angular 2+**, because it is a complete other thing technically.
2. Because we are developing and building with the dependencies tools npm (and still bower) and are pushing the final `package.json` and `bower.json` always within the release, everyone can have a look which dependency in which version is (not) available. This is technical information and is meant as *advice by the author*. This means every time a new AngularJS version will be released, there have to be done at least one angular-translate release for "official" support: we had have a look and confirm it's working. Maybe it was "needless", but who knows it before? 
3. Some build/dependency handle incompatible versions (i.e. logging), and most of them have an option to overrule this setting. If you know you what you are doing, take you control.
As bower will complain if different versions of one release are used (solution: pinning aka "resolve"), npm will simply ignore other (read: newer) versions, unless such version is required explicitly.
4. You should *never* use minified code of libraries. Regardless AngularJS, or plugin angular-translate, or what ever. First: Most users are building their application (compiling), bundling, compressing), so an already minified scripts file is needless and will not result into a "better" one. The opposite will happen. Second: You must have a full working development/debugging environment, which is not possible with minified script files (i.e. missing debug symbols, missing object names, unreadable stacktraces).


That's the general part.

----

One additional point to the compatibility in general: Obviously, not every app can be update to the most reset release. That's not possible always due different constraints. But everything is moving, regardless your (maybe not "yours") project is moving or not. 

@robertochingon 

In this case, if you are running an AngularJS of September 2012 (which is five(!) years old), you simply cannot expect updating angular-translate to latest will still work without changes. The issue shows you don't have looked into it before. Just update, and boom. Yeah, well... 🤕 

After having a look into your STO posts, the problem's history is something else.

> Howerver, I´m getting error in the call: TypeError: $translate(...).then is not a function

This means you had used an old version of angular-translate (because of the error message something `< 2.0.0`, later you said it is a `1.1`), but also you had looked into the online documentation to the current version. => Different versions will not fit.
On the one hand, this is not comfortable for users having old versions, but on the other hand we cannot take care of 5 years old documentations. Sorry, that is impossible.

> ncaught TypeError: g.has is not a function     at Constructor.$get (angular-translate.min.js:6)

Whatever, see general point 4 above. But the documentation is not right because not the matching version. Maybe an incompatibility because of AngularJS 1.1 and AngularJS 1.2. AngularJS had has history of breaking changes between minor and even patch releases.

Your options so far:
1. Stick with the 1.1, and use the documentation of *this* release. This is not available online any more, but the sources are nearly full documented. If you use the non minified version, you will see it. In a nutshell: the service `$translate()` (angular-translate 1.x) can be compared with the service `$translate.instant()` (angular-translate 2+)
2. Update to angular-translate most recent which would require updating AngularJS also.

IMHO
* If you only have to fix something, I would not start any upgrade processes in a project.
* If the project is not in maintenance mode and should be developed actively, then the dependencies and frameworks should be updated. But this would mean an AngularJS 1.6 (as of today) also

Info regarding our package metadata
* [angular-translate 1.1.1](https://github.com/angular-translate/angular-translate/blob/1.1.1/bower.json) was the last one supporting AngularJS 1.0
* [angular-translate 2.0.0](https://github.com/angular-translate/angular-translate/blob/2.0.0/bower.json) starts supporting AngularJS 1.2+ only
