### ISSUE TITLE
infinite $digest when 'put' missing translations

### ISSUE THREAD

**Issue by nvomedia** [angular-translate/angular-translate#1796]
### Subject of the issue
I want to put the missing translations in the database using the `useMissingTranslationHandler()` function. But I'm getting an infinite $digest loop when I add the $http code in the function. When I only log the missing translation like in the docs, there is no problem. 

https://docs.angularjs.org/error/$rootScope/infdig?p0=10&p1=%5B%5D

### Your environment
* angular-translate: 2.15.2
* angular 1.6.1
* chrome 61

### Steps to reproduce
You can see the code here: https://plnkr.co/edit/nl7GD7kgoMXS6XTt8Hl2

I have comment out some code in the app.js file, where the error happens. But when you enable it, there is a change that your browser will hang or crash. I have tested it in plunker, and despite the fact that the url gives an 404 error, my error is still going on.

### Expected behaviour
I want to post the missing translation ID so I can handle it in my backend controller. (saving to the database for example)

**Comment by knalli** [comment]
Sorry for the delay.

Short: no idea.

Long: The error is something AngularJS internal, but mostly when digest are.. well.. in a loop.
Also I would recommend NOT sending each error directly via HTTP, because you can produce a flood attack against your own server. That's bad.

So a proper solution (which also works around your issue): On error, invoke only a service of you (adding the label in question to an internal stack/queue). Independently and periodically, you check for content and send them as a bunch to your server. Maybe every 10 seconds (if more critical), or only every 60 seconds.
