### ISSUE TITLE
Request: Problems with the asynchronous translation

### ISSUE THREAD

**Issue by mnemotron** [angular-translate/angular-translate#1802]
Hi,

I have a problem with the asynchronous translation, like	
for( i = 0 ...)
{
$translate(breadcrumb[i].id).then(function (translation) {
					breadcrumb[i].text = translation;
				});
}

The problem is, the callback function does not know the index (i).
Other context.

Is there any way to translate a text without a callback function?

Like: var text = $translate(breadcrumb[i].id);

Thanx.

**Comment by knalli** [comment]
Hello,

thank you for contacting us.

However, this issue tracker is intended for bugs, tasks, and features for the library angular-translate only.

We highly recommend our api documentation and guide available at https://angular-translate.github.io/. Because nothing is perfect, we are welcome any improvements or suggestions found in the docs also provided as a PR.

Finally, we advise you asking common "How to... ?" questions at community boards like [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-translate) because you will reach a bigger audience. Also, providing a complete example (i.e. using this [plnkr template](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview)) might help everybody to find a proper solution faster.

Thanks.

**Comment by knalli** [comment]
@mnemotron It looks you are having issues with JavaScript respectively parallel function executions in general, but this is not the right area for this.

Thank you.
