### ISSUE TITLE
'sce' sanitize strategy makes $translate.instant and translateFilter return objects not strings

### ISSUE THREAD

**Issue by tommck** [angular-translate/angular-translate#1803]
### Subject of the issue
When using the 'sce' 

### Your environment
* version of angular-translate: 2.15.1
* version of angular 1.5.11
* which browser and its version Chrome latest

### Steps to reproduce
Plunker shows that 'sce' makes the values objects.

https://plnkr.co/edit/FUtKUQ?p=preview

### Expected behaviour
I expect that the translateFilter and $translate.instant would return strings, not objects.

### Actual behaviour
It returns a "TrustedHolderValueType" (typeof == "object")

**Comment by tommck** [comment]
It's because this line of code is just the result of `$sce.trustAsHtml`, which is an object

https://github.com/angular-translate/angular-translate/blob/c7e743bb54b18f404e7ab5b91b88f842f144bbae/src/service/sanitization.js#L79

**Comment by tommck** [comment]
Both `escape` and `sanitize` return strings.  It should be consistent, shouldn't it?

**Comment by knalli** [comment]
Structure: We have three endpoints/apis exposed by this library: directive, filter and service. Internally, the directive and the filter are using the service which ends up being only one actual endpoint/api: `$translate()` and its non-async buddy `$translate.instant()`.
However, most will use directive or filter only and will not have had an issue with this one.

As you had already discovered, I was also not happy with the change last year, but had to make a decision after a broken state. There are unit tests, but one special case had not been covered and overseen.

Coming to *sce*: the easiest way would be just returning a string, right? And because of the api is declaring a string will be returning (because we are translating only strings for strings). However, the idea of `$sce` is providing a trusted content which can be resolved within templates correctly as strings. They are not strings, but will be rendered like them. That's an AngularJS feature.

This does make sense when using our directives and filters, but can have issues when using the service. But fixing the service without having the context of the dependent components will change more.

Technically, there is currently a mismatch about signature and actual return. But semantically, this is still right: it is a (trusted) value of a string in an AngularJS app.

You can only have an issue with this, if you have the following situation:
* using the service directly (no directive nor filter)
* not injecting the translated values in a template
* instead using the values within i.e. providing in Non-AngularJS components


@tommck : What do you think of 
* adding an additional hint to the APIs result types indicating that trusted value holders can be returned (because that is missing at least); 
* and the service getting an optional opt-in flag for returning the untrusted value ([example](https://github.com/angular-translate/angular-translate/blob/c7e743bb54b18f404e7ab5b91b88f842f144bbae/src/service/translate.js#L1405-L1410))

**Comment by tommck** [comment]
Definitely should add documentation hints for this, because it was really confusing. (the TypeScript typings are wrong too :) )

So you're saying we'd have to pass an additional parameter in every instance where we wanted to just get a string back?

I'm just trying to figure out a situation where someone would ever want the TrustedHolderValueType type instead of a string.

Seems to me that the default should be string and opt-in to getting the TrustedHolderValueType

**Comment by knalli** [comment]
> Definitely should add documentation hints for this, because it was really confusing. (the TypeScript typings are wrong too :) )

We are not providing TypeScript types. Or: That is not under our control.

> I'm just trying to figure out a situation where someone would ever want the TrustedHolderValueType type instead of a string.

That's standard using templates which includes directive and filter. Your not seeing this ;)

**Comment by tommck** [comment]
> That's standard using templates which includes directive and filter. Your not seeing this ;)

Right, but they never actually want that type.. they want the string that is being rendered.  What is the value in returning the TrustedHolderValueType rather than just a string, since it's always rendered as such?

**Comment by tommck** [comment]
One fundamental issue I see here is that changing your strategy from 'escape' to 'sce' requires code changes in the rest of the app.

That doesn't seem like a good side effect to me

**Comment by knalli** [comment]
Eh.. if you are only using our directive and filter and the service's returns only in templates, you have no rewrites. Just as I said: The trusted values are using by the templates internal service.

**Comment by tommck** [comment]
right, but there are many instances where we use the javascript directly (> 125 instances in our app).

Still don't see what problem it causes to just return a string

**Comment by tommck** [comment]
the entire issue would be solved if we removed the custom code from src/service/translate.js that you pointed to and changed the `return value;` to `return value && value.toString();` in the 'sce' strategy

There are no other mentions of "trust" in the code base

**Comment by knalli** [comment]
IMHO: `value.toString()` is not correct. As I remember correctly, it was needed to call the internal function. (ofc: which is bad) But I cannot verify this at the moment.
____

Well, you have your app in mind. If have a library here used by a lot of different developers with different scales, minds and requirements. And it should fit for all. And here we go: Welcome to the unfinished field of #1101 and the beginning of the journey "where and when we have to trust the value". 🐎  (short and only valid answer: actually never 😄  )

* If I change this to the untrusted value, we will have only a solution for strategy *sce*. There is also *sceParameters* left.
* If the result is a "trusted value" (because that's what the result would be), we have a bunch of characters which *MUST* be injected fully trusted. No escaping is allowed. This will break a lot more.

And finally this changes the behaviour: I have extracted the relevant strategy of my big demo, and applied the proposed change: http://plnkr.co/edit/dMhMcIzGSMSH4UlfXc2w?p=preview Note the subtile change of the result (colored text).

**Comment by knalli** [comment]
I have added the demo an example using the filter. Eventually more understandable the the rest: trusted value holder (using `$sce`) allows html in AngularJS filter functions.

**Comment by tommck** [comment]
I understand what the $sce does, but I thought that we couldn't put HTML in our translation strings at all. I didn't think that was a goal or even desired.

That's a HUGE assumption that I made that I thought was based on reality.

**Comment by tommck** [comment]
Also, if my change would break stuff, then there are some large gaps in the tests in the code base

**Comment by knalli** [comment]
Well, if you don't want to put HTML (and others) into your app, you should simply use escape. Best method ever.

But if you want to use HTML in special cases a more controlled way, you will have the option to use `$sce` and others. But the chapter about `$sce` in the AngularJS docs is not short. That means something ;)

**Comment by knalli** [comment]
> Also, if my change would break stuff, then there are some large gaps in the tests in the code base 

I'm not sure what you have changed. But you are welcome to fix it. :octocat:

**Comment by tommck** [comment]
well, I guess I'm going to create my own service to translate to strings for use in javascript and write an ESLint rule to disallow other uses in order to avoid this issue.

I still think there's a fundamental consistency issue with it returning an object, when I'd never expect that, especially as a developer on a large project where you might not understand the "big picture".

**Comment by tommck** [comment]
> Well, if you don't want to put HTML (and others) into your app, you should simply use escape. Best method ever.

Unfortunately, that screws up simple "&" being in a string

**Comment by tommck** [comment]
> I'm not sure what you have changed. But you are welcome to fix it. :octocat:

How did I know you were going to say that? 😄 

All I changed was 3 files.. the `return value && value.toString()` thing mentioned above along with fixing one unit test that unwraps and removed the special code in the translate service that handles unwrapping.

With those changes, all unit tests pass on all scopes.  Nothing is testing to make sure HTML is rendering properly through translation.

As far as adding tests, I'm apparently not sure what the assumptions of functionality are, since I didn't even think it was supposed to allow HTML content. Do we have a list of things that need to be tested?

**Comment by knalli** [comment]
> How did I know you were going to say that? 😄
That is still a community-driven project, help is welcome always.
____
I've added all current strategies in this [WIP branch](https://github.com/angular-translate/angular-translate/tree/feature/sce_testing).

I'm still missing one special case, tests with special unicode chars, and maybe initial development of new/better strategies.

**Comment by tommck** [comment]
Oh nice. Looks like some good tests in there.. I'm sure my changes would break those :)
