### ISSUE TITLE
How to escape a clickable link in a string with user-supplied data in it?

### ISSUE THREAD

**Issue by distinctdan** [angular-translate/angular-translate#1806]
I'm trying to interpolate a string that has both html and user-supplied data in it, like "You have a new message: [messageTitle]", where clicking the message title takes you to the message. So, the link needs to be html, but the message title must be escaped to prevent XSS. However, I haven't been able to find an escaping strategy that renders this correctly.

Localization best practices say you should keep html out of strings, so my string looks like: 
`You have a new message: {{startLink}}{{messageName}}{{endLink}}.`

And the args are:
```
  {
    startLink: '<a href=\'/messages/{{message.id}}\'>',
    messageName: '{{message.name}}',
    endLink: '</a>'
  }
```

How do I escape this properly? Here's a plunkr: http://plnkr.co/edit/lrp6J3MpRlGge75p6QYh?p=preview

**Comment by distinctdan** [comment]
We're already using the sprintf library in our project, so for now I wrote a simple directive that interpolates the args into the string and renders that html to the DOM during the compile phase of the directive. Then, angular will actually fill in the {{ }} placeholders when it compiles the directive's inner html, so there's no risk of XSS. I'm still curious if this can be done with angular-translate though.

Here's the updated plunker with my directive: http://plnkr.co/edit/06zvQ0ISdDOSHRa7TMh6?p=preview

**Comment by knalli** [comment]
Simply: Don't. ;)

The problem is: there is no point whether the code (library, our point of view) could determine which role some of your parameters have. Without an additional parameters type meta model (param a is html safe, param b not), this is an impossible task.

So there are the following options left:

1. Only the translation itself defines (valid) HTML, but no parameters. In this case, you define a parameters-only escaping/sanitizing strategy because you would declare all translations texts as fine/secured. As you are shipping your texts on your own, you can treat them like any other internal resource file.
2. You request partial translation parts (maybe requested with the bulk/batch mode) and combine them afterwards to a custom translation. In this case, you can combine different request modes and result bindings.
3. The last option would be to reduce all relevant security options and adjust them all correctly for each translation and parameter. Actually not an option and never a recommendation. (_But technically you could…_)

And some final words: You should not have to build separated HTML in the translations (a standard recommendation about translating). So go with a simple `You have a new message: {{linkAsHtml}}` (if this have to be dynamically), but my recommendation would be `You have a new message <a href="{link}">{name}</a>` (I know, it depends). Maybe that's a silly example (because of demo), because otherwise I would reconsider whether this additional must be in the translations after all.
This is a reflex by developers extracting everything and making it more reusable. But it should not make the thing too complex and reducing security.

Regarding your question about sprintf: I don't get it. Where is the difference? It is actually nothing else than the interpolation, isn't it? Maybe this would be an alternative interpolation strategy (instead of AngularJS, with `sprintf`), but I don't know if this is worth enough.

**Comment by distinctdan** [comment]
Unfortunately, this is a fairly common use case. "Don't" simply isn't an option. Your example isn't an option because if you do `You have a new message: {{linkAsHtml}}`, that doesn't solve the problem. You're still interpolating html and user-supplied data in the same string. In your second one, putting html in your strings is an option, but it's considered a bad practice because it gives your translators an opportunity to accidentally mess stuff up. 

It seems the issue is really that you guys are using the same characters as angular, {{ }}, to define a variable. So in, `You have a new message: {{startLink}}{{messageName}}{{endLink}}`, `startLink` and `endLink` should be handled by angular translate, and shouldn't be escaped at all. However, `messageName` is a normal angular expression, and should be ignored. If you guys had a way to change your characters that define an expression, it could work. C# uses things like `{0}` and `{1}`, while sprintf can do positional or named args like `%1$s` or `%(linkStart)s`

**Comment by knalli** [comment]
@distinctdan Ehm, no, there are only variables/parameters. Nothing else like "a normal angular expression". Even this only works if it can be resolved by the given payload -- implicitly looked up by using the directive's scope, or explicitly given using filter (since AJS 1.2) and service api because both lacking a scope by design.

So, you can replace the default interpolation service with your own implementation (already said) to use other leading/trailing separators, but you won't get out of this dilemma. 

Well, until: Your write an interpolation service using two different interpolation strategies itself. But then you have to manage the different usage of two different types of parameters. However, because the interpolation strategy must care of the sanitization/escaping, you can control everything.
