### ISSUE TITLE
Why not use $translate.translationTable directly ?

### ISSUE THREAD

**Issue by wxy1995** [angular-translate/angular-translate#1822]
### Subject of the issue
I want to use $translate service in my controller, but find that i have to execute function `init()` in the callback of `$translate()`. Otherwise, page will throw error. Also, i have to write too many variables in one controller, and repeat in other controller.

Example, 
```
// Case 1: hava to write in callback
app.controller('DemoOneCtrl', ['$translate', function ($translate) {
    $translate('TITLE_DEMO').then(title_demo => {
        $scope.init();
    });
}]);
// Case 2:  write too many variables and repeat
app.controller('DemoTwoCtrl', ['$translate', function ($translate) {
    $translate(['TITLE_DEMO_1', 'TITLE_DEMO_2', 'TITLE_DEMO_3']).then(res => {
        $scope.translationTable = res;
        $scope.init();
    });
}]);
app.controller('DemoThreeCtrl', ['$translate', function ($translate) {
    $translate(['TITLE_DEMO_2', 'TITLE_DEMO_3', 'TITLE_DEMO_4']).then(res => {
        $scope.translationTable = res;
        $scope.init();
    });
}]);
```

### Expected behaviour
It's very inconvenient for me. Why not bind translationTable on $translate, so that we can use `$translate.translationTable.TITLE_DEMO` in any one controller directly?

Example,
```
var statusText = (data.status === 1) ? $translate.translationTable.SUCCESS_TEXT : $translate.translationTable.ERROR_TEXT;
```

What do you think of this idea？Or, is there any best practice to solve this problem?

**Comment by knalli** [comment]
> Why not bind translationTable on $translate

Because you (or your code) is not in charge of maintaining the state of this table. Is is already loaded? Will it be replaced? Will it be appended by additional parts? You (or your code) have no idea. That's because our plugin is managing this for you -- including changing languages, featuring fallback decisions, dynamic parameter injection and even asynchronous and partly loading.

This is a translation service api which helps you translation text for keys. So deal with it. 🐰  This is not a blob/text string container. 
Maybe you don't need the translation api service overhead; in that case a simple JSON map is enough.
