### ISSUE TITLE
What is the correct syntax for interpolating a variable inside the filter's interpolateParams?

### ISSUE THREAD

**Issue by dmigliorisi-we** [angular-translate/angular-translate#1826]
### Subject of the issue
I'm trying to use the translate filter with pluralization and I've gotten it working without any issue when I use static values but can not figure out how to get the filter to recognize scope variables.

### Your environment
* angular-translate v2.17.0
* angular v1.5.7 
* All browsers

### Steps to reproduce
`{{ 'SELECTED_ASSIGNEES_COUNT' | translate:"{COUNT: $ctrl.selectedAssigneesCount }":"messageformat" }}`

### Expected behaviour
`$ctrl.selectedAssigneesCount` should be interpolated.

### Actual behaviour
`$ctrl.selectedAssigneesCount` is undefined, presumably because there's no reference to the current scope. (https://github.com/angular/angular.js/commit/8863b9d04c722b278fa93c5d66ad1e578ad6eb1f)

**Comment by dmigliorisi-we** [comment]
I've gotten this to work with the directive approach. I suppose I'll have to go that route for now.

**Comment by knalli** [comment]
@dmigliorisi-we Yep, the filter's scope is undefined for years already. You are encouraged to replace your `$ctrl` approach with the much more modern way using `bind controller`. 

More refs
* https://blog.thoughtram.io/angularjs/2015/01/02/exploring-angular-1.3-bindToController.html

**Comment by knalli** [comment]
Also you cannot rely on the scope and a on-demand expression as you did with `"{COUNT: $ctrl.selectedAssigneesCount }"`.

This is fine because it uses a pre-evaluated expression (not evaluated within the filter):

`{{ 'SELECTED_ASSIGNEES_COUNT' | translate:{COUNT: $ctrl.selectedAssigneesCount }:"messageformat" }}`

Maybe you also define messageformat as default which would remove the need of defining it.
