### ISSUE TITLE
Message bundles have revision hashes

### ISSUE THREAD

**Issue by kensplanet** [angular-translate/angular-translate#1828]
My project structure is as below. For cache bursting, we add a revision hash to the file names using Grunt.

message_bundles
- default
-- en.0ffb29ba.json
-- fr.058b3ea2.json
- brand1
-- en.8a80554c.json
-- fr.9a80654c.json
- brand2
-- en.3a40554c.json
-- fr.1a80150c.json

This is my Angular Translate configuration. We have default master message bundles and the child brand bundles inherit from the parent.

```javascript
$translateProvider
    .useStaticFilesLoader({
      files: [ {
        prefix: 'message_bundles/default/',
        suffix: '.json'
      },{
        prefix: 'message_bundles/' + {{BRAND}} + '/',
        suffix: '.json'
      }]
    })
    .preferredLanguage('en')
    .registerAvailableLanguageKeys(['en', 'fr'], {
      'en.*': 'en',
      'fr.*': 'fr'
    })
    .useSanitizeValueStrategy('sanitize');
```
	
This doesn't work since the file names have revision hashes. Is there any way to make Angular Translate ignore the hashes?

### Environment
* version of angular-translate - 2.17.0
* version of angular - 1.4.4
* which browser and its version - Google Chrome | 64.0.3282.140 (Official Build) (32-bit) (cohort: 64_140_win)

**Comment by knalli** [comment]
Ehm.. how should this even work in theory? If angular-translate aka the browser skips notice about the hash, the server will not find the corresponding resource. Because the resources (like the translation files) have *changing urls*, you are making the whole stuff using hashes. 

Skipping them would bypass the idea of the cache. That does not make sense.

So, if you have decided to use such a pattern, you have the following options:

1. Configure the urls probably with the hash. If you have a post processor already (like Webpack), you could maybe inject the dynamic url of the resulting artefacts while building them. Or: It looks like you have something similar for your branding stuff. Either you inject the actual path, or you inject the information about the path segments (i.e. via a dynamic generated JSON file). 
2. Alternatively, you could rethink the whole thing (depends on the size of files): If you are already building an "app", you can inject the actual translations without an async loading part. Definitely worth if the translation files are small.

**Comment by kensplanet** [comment]
For Approach1, the `{{BRAND}}` value is available to the Angular application at runtime through a jQuery AJAX call it makes even before bootstrapping the Angular app. The app does have the dynamically generated revision details generated through Grunt.

```javascript
fileRevMap = {
	"message_bundles/default/en.json": "message_bundles/default/en.xxxxxxxx.json",
	"message_bundles/default/fr.json": "message_bundles/default/fr.xxxxxxxx.json",
	"message_bundles/brand1/en.json": "message_bundles/brand1/en.xxxxxxxx.json",
	"message_bundles/brand1/fr.json": "message_bundles/brand1/fr.xxxxxxxx.json",
	"message_bundles/brand2/en.json": "message_bundles/brand2/en.xxxxxxxx.json",
	"message_bundles/brand2/fr.json": "message_bundles/brand2/fr.xxxxxxxx.json"
	.
	.
	.
	and so on for the rest of the brands
}
```
But even with these details, how do I inject them in the `$translateProvider` code above since the revision hashes for all the files could be different. I was thinking if I could somehow intercept the REST call which Angular Translate makes when fetching the resources, I could somehow transform it to the one present in the `fileRevMap` variable above.

**Comment by knalli** [comment]
You can build your own custom loader (see docs) doing whatever you want. It is only a function (service).

**Comment by kensplanet** [comment]
So, here is what I have done. I intecepted the request using `$httpProvider` and modified it. `fileRevMap` is my map containing the revisioned file names.

```javascript
 $httpProvider.interceptors.push(function (fileRevMap) {
    return {
      request: function (config) {
        config.url = fileRevMap[config.url] || config.url;
        return config;
      }
    };
  });
```
So, no changes from Angular Tanslate. So, you can close this.
