### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by alejnavarro** [angular-translate/angular-translate#1830]
hi, i'm just ending the view of the project and notice that you don't have any information in spanish, i wonder if you want to translate something into it, because if you want to, i'll be glad to do it for you, if you let me.

**Comment by knalli** [comment]
@alejnavarro  Thank you very much for your contribution effort.

However, we have [decided](#1671) last year to remove any localized informations/texts (incl. German, which is native for the most contributors) because we do not have the time and ability for maintaining all translated guides and documentations.
