### ISSUE TITLE
AngularJS crashes when trying to add an array to ng-bind-html

### ISSUE THREAD

**Issue by cschwaderer** [angular-translate/angular-translate#1871]
### Subject of the issue
I have translate strings which contain HTML tags, so I need `ng-bind-html` for the HTML tags to be rendered. That works pretty well in general. However, yesterday, I accidentally put in an array instead of a string - AngularJS crashed at that point with the famous `10 $digest() iterations reached. Aborting!` message. Took me some hours to find the cause of this. So,  catching that error with a more meaningful message would be handy.

Note: I don't know whether this is actually a problem of angular-translate or of AngularJS itself. However, `ng-bind-html` works with an array and without `'| translate`. Same goes for a built-in filter like ` | uppercase `. So, it seems that the reason is the translate filter.

### Your environment
* 2.8.1 version of angular-translate
* AngularJS 1.7.5
* Tested both in Firefox and Chrome

### Steps to reproduce
* Include ngSanitze
* Add in template `<p ng-bind-html="['some_array'] | translate "></p>`

See Plunker: [https://plnkr.co/MWca96HNfHp9Ck4Xk2Os?p=preview](https://plnkr.co/MWca96HNfHp9Ck4Xk2Os?p=preview)

When passing a simple string, there is no error (and of course, no translation since I didn't provide any in the Plunker, but that's not the point.)

### Expected behaviour
Angular translate should display a meaningful warning/error message like: "Cannot process array as translate string: ['some_array']" and rest of controller should continue executing normally.

### Actual behaviour
A very unspecific error message is displayed:
> Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations:... 

and AngularJS stops executing the controller from then on.

**Comment by knalli** [comment]
@cschwaderer  Thank you for getting in touch.

When using in templates, it looks like a stateful AngularJS filter (`$stateful`, see https://docs.angularjs.org/guide/filter#stateful-filters) is not compatible with an array as result.

See this:
```
app.filter('demo', function ($filter) {
  const f = function (x) {
    const result = {}
    x.forEach(v => result[v]=v)
    return result;
  };
  f.$stateful = true; // << here
  return f;
});
```

If this filter is used in a template like `<p ng-bind-html="['some_array'] | demo "></p>`, it will crash also. If it is not stateful and it will return an object.

As requesting multiple values (in an array) per filter/function is not forbidden per se (however, it would be not regular), I don't see we can handle this speaking of displaying a information. Just because the library (aka the filter function) does not know in which context it is being called. Sorry.
