### ISSUE TITLE
Angular@1.8.0 support 

### ISSUE THREAD

**Issue by ezankov** [angular-translate/angular-translate#1903]
### Subject of the issue
Right now all angular-translate packages describe angular dependency as angular` ">=1.2.26 <=1.7"` which forces npm to install the extra package in the case when we use angular@1.8.0.

### Your environment
* version of angular-translate : 2.18.1
* version of angular : 1.8.0
* which browser and its version: latest

**Comment by knalli** [comment]
Hi @ezankov,

thank you for bringing this up. Although I think you can override the (transitive) dependency angular with an explicit override in your package.json, it would be good increasing support. However, that means everything must be checked against this (said that, I'm atm not aware of the 1.8.0 release log). 

You can speed up this with contributing 1.8er tests like 7a44ddf7fcd076d7515f0f3fb1293c6b5d0749d0.

**Comment by evilaliv3** [comment]
@knalli @ezankov : actually we are using angular-translate with angular 1.8 as well in @globaleaks and i just noted this issue.

Would you please clarify which is the impact of this?

**Comment by knalli** [comment]
> Would you please clarify which is the impact of this?
As I already said: I'm have not looked into the 1.8 release log yet. There is no test against 1.8. Simply "no idea". Generally, it should work except there are breaking changes in the used APIs of AngularJS.

The only reason why there is the limit `<=1.7` is because we cannot ship a release stating support without having testing it. Somehow obviously, I think :)

**Comment by evilaliv3** [comment]
Sure! this was clear to me thank you @knalli i was just in doubt about possibly getting angular limited to 1.7 due to the limit imposed in angular-translate but actually after verifying i see that i get installed correctly 1.8.0.

If worth for you to know we are using successfully angular-translate with angular 1.8.0 since its release and for the use we do i've not noticed any failure.

**Comment by knalli** [comment]
Available with the recent [2.18.3](https://github.com/angular-translate/angular-translate/releases/tag/2.18.3). Thanks @evilaliv3
