### ISSUE TITLE
“SameSite” attribute warning

### ISSUE THREAD

**Issue by andreicvasniuc** [angular-translate/angular-translate#1906]
### Subject of the issue
This warning appears in the browser console:
Cookie “NG_TRANSLATE_LANG_KEY” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

### Your environment
* angular-translate version: 2.18.3
* angular version: 1.8.0
* browser: Firefox 80.0.1 (64-bit)

### Steps to reproduce
Just open your demo https://plnkr.co/edit/XorWgI?p=preview in Firefox and open the console.

### Expected behaviour
No warnings.
It would be great if you allow us to pass options to the cookies put method in order to set "secure" and "samesite" options which are implemented in angular-cookies already => $cookies.put(key, value, options)  

### Actual behaviour
Show warning: Cookie “plnkr.access_token” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by knalli** [comment]
Please consider to add your own storage implementation. 

As you can see:

https://github.com/angular-translate/angular-translate/blob/026674de030827e0809972c0351f8b97394391db/src/service/translate.js#L692-L694

is only using the public api `$translateProvider.useStorage(…)` and where`$translateCookieStorage` is simply the service [storage-cookie.js](https://github.com/angular-translate/angular-translate/blob/026674de030827e0809972c0351f8b97394391db/src/service/storage-cookie.js). Actually very simple, as that is only such complex because of the backwards compatibility to the older `$cookieStore`. In a nutshell, the storage provider must implement `get` and `put` as [mentioned in the guide](https://angular-translate.github.io/docs/#/guide/11_custom-storages).
