### ISSUE TITLE
IOS cordova When i upgrade the AngularJs to 1.8.2 the words will be missed which was been translated.

### ISSUE THREAD

**Issue by LeoHYS** [angular-translate/angular-translate#1912]
### Subject of the issue
I'm using the AngularJs 1.8.0 and angular-translate is 2.18.4. the issues are not appear, but we need to upgrade the AngularJs to 1.8.2 some label will be disappeared in Ios cordova. other platform is normal.

### Your environment
angular-translate version2.18.1
angular version1.8.2
ios cordova 5.1.1

### Steps to reproduce
The code just like this
<span class="label" translate="action.title"></span>

Any one have faced this issue?could someone can help?

**Comment by knalli** [comment]
Hello,

i would recommend to look into the app with a debugger which will provide you with additional loggings. Maybe this will show you more details.

Otherwise: As we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.
