### ISSUE TITLE
feat(): $translatePartialLoader.addPart should return a promise

### ISSUE THREAD

**Issue by ghost** [angular-translate/angular-translate#197]
You could then add parts in the resolving process of a route and open the page as soon as the translation is available.

Currently it returns the $translatePartialLoader itself. The change would break chained calls.

An additional method addPartAndReturnPromise would not break this.

**Comment by dwilt** [comment]
I didn't find the answer I was looking for when I got here. I came because I was trying to find out why `$translatePArtialLoader.addPart('whatever')` didn't return a promise. That just made total sense to me. I was ultimately trying to figure out how I can stop my view from loading until all of the required translations for that view loaded via ui-router's `resolve`. After reading what @jedmao came up, I thought I could put together a better solution. Overall, I think the problem with jedmao's code is that it's not returning a _promise_ but just calling `$translate.refresh()` after calling `addPart` without guaranteeing that his translations loaded - after all, they are loading asynchronously. It was close so I just made the following adjustments:

In my `resolve` for my `$stateProvider`, I call `loadParts` on my `translations` service:
```
resolve: {
    languages: (translations) => {
        return translations.loadParts(
            'views/language-selection'
        );
    }
}
``` 
The key is that loadParts returns a promise (as I mentioned above), and it looks like this:

```
// My translations service
loadParts() {
        var parts = Array.prototype.slice.call(arguments), // convert arguments (parts) to a true array
            deferred = this.$q.defer(),
            totalLoaded = 0, // this represents how many parts/files have actually loaded
            total = arguments.length; // this is how many parts we're trying to load

        parts.forEach((part) => {
            this.loadPart(part).then(() => {
                totalLoaded += 1;

                if(totalLoaded === total) {
                    this.$translate.refresh();
                    deferred.resolve();
                }
            });
        });

        return deferred.promise;
    }
```
I take in however many "parts" I pass in, iterate over each of them and call my `loadPart` method for each. `loadPart` returns a promise as well and on `then`, I iterate the `totalLoaded` by 1 and then check to see if the `totalLoaded` matches the `total` passed in, and if it does, I resolve the promise for `loadParts`. This gives me a true accounting to make sure that everything has loaded before I resolve. Once that matches, I then call `$translate.refresh()` and resolve my promise.

Here's my `loadPart` method:
```
loadPart(part) {
        var deferred = this.$q.defer();

        var listener = this.$rootScope.$on('$translatePartialLoaderStructureChanged', () => {
            listener();
            deferred.resolve();
        });

        this.$translatePartialLoader.addPart(part);

        return deferred.promise;
    }
```
The `listener` var is so I can remove the listener from $rootScope once I'm done with it.

**Comment by napstercake** [comment]
@jedmao maybe this is not part of  the issue here but I do not have any other site where I can make my question:

This code loads the translate by components, lets say I don't want to load "index", I need to load "home" because I need the user log-in.

```javascript
.config(function($translatePartialLoaderProvider) {
  $translatePartialLoaderProvider.addPart('home');
});
```

My question is, where should I put this code? If I left this code on my config this will execute when my app load for the first time and it seems I can not put this inside a controller:

Any advice?

**Comment by dwilt** [comment]
@napstercake `$translatePartialLoader.addPart('home`);` should do it for you.

@jedmao I'm having issues where the translation tables are not translated in my app even though I added a component during the config phase like @napstercake is doing and `$translate.refresh()` resolved. Any ideas?

**Comment by jedmao** [comment]
@dwilt I haven't touched Angular in over a year now, nor do I have access to my eventual configuration; however, @prabinv might.

**Comment by napstercake** [comment]
@dwilt if I use $translatePartialLoader inside of a controller I always have this error:Unknown provider: $translateProviderProvider <- $translateProvider <- myController also if y use just use $translatePartialLoader.addPart('home') where should I specify my URL to consume my rest that will retrieve the translation table ONLY for home. :(

**Comment by knalli** [comment]
You cannot use providers in non config phase contexts, like a controller.

**Comment by dwilt** [comment]
@knalli From here: http://angular-translate.github.io/docs/#/guide/12_asynchronous-loading (about midway down the page)

> translatePartialLoaderProvider configures $translatePartialLoader which means you're able to inject $translatePartialLoader into your controllers and services to make use of it. But why do you want to? As you can add a translation part to the loader via the provider, you can also do so with the provided service to manipulate loader state at runtime. So what does that mean? It means, you just have to inject the loader and use that one to add additional translation parts.

> Let's say we have a ContactCtrl within our contact module, things could look like this:
```
angular.module('contact')
.controller('ContactCtrl', function ($scope, $translatePartialLoader) {
  $translatePartialLoader.addPart('contact');
});
```
> That wasn't hard, right? So what happens here is we manipulate our loaders state during runtime. This makes sure that angular-translate only loads specific translation data when we really want to. Once you added a new part, $translatePartialLoader fires an $translatePartialLoaderStructureChanged event.

**Comment by knalli** [comment]
Yeah. `$translatePartialLoader` and `$translate` are regular services and available in the regular context (services, controllers, directives, filters). But the providers like `$translatePartialLoaderProvider` or `$translateProvider` are only available in the config phase.

**Comment by napstercake** [comment]
Where is the call to the REST service that retrieve me the translation table if I use only 

```javascript
$translatePartialLoader.addPart('contact');
```

In the config? If I call to my REST from the config it will fire everytime the page refresh right? So the concept of partialLoader is to load translation table on demand. I'm so confuse.

**Comment by knalli** [comment]
You use `$translatePartialLoaderProvider.addPart()` in the config phase, and this will load all registered parts. After you have added additional parts *after* the config phase via `$translatePartialLoader.addPart()`, you will have to invoke `$translate.refresh()`.
