### ISSUE TITLE
Discussion: adding ltr and rtl support

### ISSUE THREAD

**Issue by DWand** [angular-translate/angular-translate#260]
There were several question about support of the ltr and rtl languages.
Let's think how we can add this feature to the angular-translate.
Pinging @PascalPrecht, @knalli, @sgara, @tspaeth here.

**Comment by poshest** [comment]
It would be great if [these files](https://github.com/angular/angular.js/blob/master/src/ngLocale/angular-locale_ar.js) could have the following attributes added, as they appear in the [jQuery datepicker i18n files](https://github.com/jquery/jquery-ui/blob/master/ui/i18n/datepicker-ar.js)

    dayNamesMin: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
    isRTL: true,
    showMonthAfterYear: false,
    yearSuffix: ''

Can't build as good a native datepicker as the jQuery one without these.  And by at least adding `isRTL` (or `direction` as in #604), a developer could easily add their own ng-class for RTL languages

**Comment by Chexpir** [comment]
@PascalPrecht What is happening with that directive that you commented on Dec 20, 2013? it sounds like the right approach to me. I am about to add it in myself in my project.

**Comment by tspaeth** [comment]
@Chexpir As the RTL-implementation is still open, it has not been implemented yet. But we're happy if someone with knowledge could help out on a RTL implementation/feature :-)

**Comment by Chexpir** [comment]
I think internally, angular-translate should contain whether each language is RTL or not. As angular-translate doesn't save all the world languages, it should be implemented in the structure we use to provide languages.
I don't have angular-translate knowledge, so maybe I can help on the implementation, but I need clear guidelines on the design bit.

**Comment by innerpeace0** [comment]
How about taking the L20n approach and letting the localizer decide?

A simple solution might be to use the css direction property. It can be applied to any element.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
