### ISSUE TITLE
$translate('key') does not return the value but a promise in 2.0.0 ???

### ISSUE THREAD

**Issue by BerndWessels** [angular-translate/angular-translate#388]
Hi
I upgraded to 2.0.0 and now doing:
var text = $translate('key');
returns an object and not the string value anymore!

Is that right? All documentation still says that it should return the string value.

Cheers
Bernd

**Comment by vedmack** [comment]
Since I found this thread for the same reason I'll just leave a notice that you can use the [$translate.instant()](http://stackoverflow.com/questions/21975794/how-to-use-a-promise-inside-an-object-literal/22349912#22349912) , [read docs for more](http://angular-translate.github.io/docs/#/guide/21_migration-guide)

**Comment by thelordgabo** [comment]
Thanks @vedmack that works, you save me a lot of time.

**Comment by temitope** [comment]
@vedmack thanks as well. huge time save. wasnt expecting the promise return. instant() was clutch

**Comment by rodrigograca31** [comment]
Thanks @vedmack it works perfectly!
