### ISSUE TITLE
Undefined preferred language when using determinePreferredLanguage()

### ISSUE THREAD

**Issue by chrisie** [angular-translate/angular-translate#563]
I have the following setup in my module config:

```
$translateProvider.fallbackLanguage('en');
$translateProvider.useLocalStorage();
$translateProvider.useSanitizeValueStrategy('escaped');
$translatePartialLoaderProvider.addPart('relinc_ui');
$translateProvider.useLoader('$translatePartialLoader', {
  urlTemplate: '/cxf/relinc-service/language/translations/{part}?lang={lang}'
});
$translateProvider.registerAvailableLanguageKeys(['en', 'ar']);
$translateProvider.determinePreferredLanguage();
```

Everything works fine when the browser sends an en_\* or ar_\* locale, however when the browser sends a locale which is not registered in the available language keys I just see untranslated keys in my UI and I see "undefined" as language key in my local storage. It seems to me that this is due to the implementation of the negotiateLocale function which doesn't return anything if the preferred locale is not found in the available languages.

What is even worse than that is that if at some later point in my application I do `$translate.refresh()` I get the error "No language key specified for loading.". From what I understand from going through the code with a debugger every time the $translate function is called the preferredLanguage (which in this case is undefined) is pushed in the $fallbackLanguage array which is what later causes the error in `$translate.refresh()`.

Is there something wrong in my configuration or is this an angular-translate issue?

**Comment by swisstofu** [comment]
One question about this topic, I would like to use `determinePreferredLanguage` to determine preferred language (yes, not a surprise!) for the user, but only his locale is included within `$availableLanguageKeys`. But this is not working as the method `negotiateLocale()` just returned the given locale by default if not found in availableLanguage array. I would say that it should return the `$fallbackLanguage` instead, shouldn't it ? otherwise user can have a non supported locale as preferred. What do you think ? 

thanks for your feedback
