### ISSUE TITLE
Partial translations not lazy loading when using with router-ui resolve

### ISSUE THREAD

**Issue by koblass** [angular-translate/angular-translate#611]
Hi,

I'm trying to get the translations to be loaded lazily by adding the "addPart" within one of the resolve method in my router, but this is not working.

Here is the code:

    locales: function($translatePartialLoader, $translate) {
        $translatePartialLoader.addPart('contacts');
        console.log('addPart');
        return $translate.refresh();
    }

When I load the application I can see the "addPart" logged in the console, but the translations are not loaded and the file has not been loaded (not present in the network).
However, when I navigate within the application the partical is loaded immediately and everything works as excepted.

Do you have any idea why ?

Best regards
Daniel

**Comment by ptgamr** [comment]
Any news on this?

I put addPart in resolve(), then it does not work.
I put addPart in the .run() section then it works.

Very strange!

**Comment by DWand** [comment]
@ptgamr, do you call the `refresh` method of the `$translate` service?

**Comment by ptgamr** [comment]
Yes I do.
@all: after upgrading to angular-translate to 2.5.2, this does not happen any more. It's all good now.

my bower.json:
"angular-translate": "~2.5.2",
 "angular-translate-loader-partial": "~2.5.2",
"angular-translate-loader-static-files": "~2.5.2",

**Comment by juristr** [comment]
Hi guys, not sure I'm having the same issue, but maybe.

I'm having a modular application structure, where each module loads its localized messages through the partial loader. I configure it in the main module

```javascript
.config(function($translateProvider) {
    $translateProvider.useLoader('$translatePartialLoader', {
      urlTemplate: './locale-{lang}.json'
    });

    // fallback language
    $translateProvider.preferredLanguage('en');
  })
```

..and then each module adds its parts

```javascript
.config(function($translatePartialLoaderProvider) {
    $translatePartialLoaderProvider.addPart('mymodule');
  })
```
So far so good, the loading of the locale files seems to work properly. The issue I'm experiencing is that when refreshing the page, the language isn't set properly on the `$translate` service. Since I'm setting it based on the user's preferences I **added a route resolve** to make sure the controller and the page don't load until I've got the user and set the language on the `$translate` service. Something like this:

```javascript
$stateProvider
      .state('home', {
        url: '/',
        templateUrl: 'module_page.html',
        controller: 'DemoController',
        controllerAs: 'vm',
        resolve: {
          currentUser: function($log, $q, $translate, user){
            var deferred = $q.defer();
            user.getCurrent()
              .then(function(result){
                $log.debug('Route resolve. Setting lang to ' + result.language);
                // set the language based on the user's preferences
                $translate.use(result.language);
                
                $log.debug('Route resolve. Lang is: ' + $translate.use());
                
                // refresh (not even sure this is needed)
                $translate.refresh()
                  .then(function(){
                    $log.debug('$translate.refresh. Lang is: ' + $translate.use());
                    deferred.resolve();                    
                  });

              });
              
            return deferred.promise;
          }
        }
      });
```

But it doesn't work. Although I'm setting the language to "de", invoking `$translate.use()` returns "en" (the preferred language).

What's interesting is that if I add a separate resolve on the router state definition

```javascript
    $stateProvider
      .state('home', {
        url: '/',
        templateUrl: 'module_page.html',
        controller: 'DemoController',
        controllerAs: 'vm',
        resolve: {
          currentUser: function($log, $q, $translate, user){
            // same as above
            ...
          },
          
          ensureLanguage: function($translate){
             $translate.use('de');
             return $translate.refresh();
          }
        }
      });
```

...then it surprisingly works?!? I fear I'm doing a really silly mistake somewhere...Could anyone take a look at it?? Here's the **Plunker**: http://plnkr.co/edit/pb8qO3J604QNri0Wf7uz?p=preview

**Comment by DWand** [comment]
Hello, @juristr.

You have to call the `$translate.refresh()` method only if you want to add or delete parts in runtime. As long as a whole structure of translation parts is constructed during the configuration phase you can freely omit this call.

Also, the `$translate.use()` method returns a promise. I think, it would be better to wrap the following code into its `then` method like this:

```js
$translate.use(result.language).then(function(){
  $log.debug('Route resolve. Lang is: ' + $translate.use());
  deferred.resolve();
});
```

I cannot guarantee that this code will solve the issue. Just a little guess.

**Comment by juristr** [comment]
@DWand I could swear I verified whether `use()` returns a promise...but yea...indeed :smile: 
Your suggestion seems to solve my issue, thx a lot :+1:

**Comment by islemus** [comment]
Hello guys,
I would like  to point out that while the issue raised by  @koblass and  @ptgamr is fixed in version 2.6 it reappears in the release 2.7.0.
I.E. in the plnkr http://plnkr.co/edit/HJpx4uM6DdBmJBqbfTRw?p=preview adding $translate.use('fr') in the resolver will solve the issue in 2.6.1 but not in 2.7.0

**Comment by tspaeth** [comment]
set a $translate.use('fr') in the config block also. Then it'll work.
There is really some things to clean up by the usage and "play together" of preferredLanguage,use,fallbackLanguage...

**Comment by islemus** [comment]
Indeed, adding a  $translateProvider.use(); in the config block solves the issue in 2.7.0

Thanks !
