### ISSUE TITLE
One-time Binding in angularjs 1.3.0.-rc2

### ISSUE THREAD

**Issue by david-hollifield** [angular-translate/angular-translate#738]
If I use angular's new one-time binding syntax on my translated values, shouldn't the watch be removed after the translate value is defined?

I use something like `<h3>{{::'FeaturedProducts' | translate}}</h3>`, but I still see a watch in Batarang.

I'm not sure if this is a bug in angular, angular-translate, or my misunderstanding of how the on-time binding should work, but this seems like a perfect scenario to use the one-time binding feature.

BTW, I'm using latest 2.4.0 of angular-translate

**Comment by ajwhite** [comment]
Just happened to come across this. I've been working on a solution for one-time binding the translations with an extension to `pascalprecht.translate`, https://github.com/ajwhite/angular-translate-once

**Comment by david-hollifield** [comment]
@ajwhite Nice!

**Comment by JerryBels** [comment]
For now I simply define my translations in the controller using $translate service, and then use a regular one time binding :: in the view. I guess it's the best I can do until angular-translate adds the :: functionnality to its filter and such ?

**Comment by JerryBels** [comment]
For now I simply define my translations in the controller using $translate service, and then use a regular one time binding :: in the view. I guess it's the best I can do until angular-translate adds the :: functionnality to its filter and such ?

I don't really want to use your extension, @ajwhite , because I don't want to have to define an HTML element for every piece of text I want translated, since I actually rely heavily on the translate filter :/

**Comment by JerryBels** [comment]
@ajwhite actually, a question : do you think the performance gain worth installing your extension and adding elements to bind translations to ? Wouldn't the HTML be more heavy, so this nullify the improvement ?

**Comment by ajwhite** [comment]
Great question @JerryBels. I'd be quite interested in doing some performance tests on that theory. It may add to the initial phase of constructing the DOM, but I can't say for sure how much overhead it will add.

Would be interesting to do a test with 100, 1,000, and 10,000 elements versus filters, invoke a few digest cycles, and see how things look

**Comment by JerryBels** [comment]
Hey, thanks for answering :) Are you planning to run these tests ? If so, I would be very interested if you could give your conclusions here whenever it's done !

I must say I don't really know how to run that kind of tests myself :/

**Comment by ajwhite** [comment]
@JerryBels -- probably not for a little while. I welcome you to submit an issue and either myself or a member from the community will pick it up at some point :)

**Comment by tangorri** [comment]
Hi,
using ::oneTimeBinding.
I meet the same problem, on certain rare circonstances the app fails to translate key (because of asynch loader). I agree I should have think about it, but it should be indicated as 'dangerous' in documentation. Removing watchers is usefull because we can use diretive in massive repeated loop...

**Comment by mebibou** [comment]
Would this work `{{::value = ('FeaturedProducts' | translate)}}`? I haven't tried though

**Comment by ajwhite** [comment]
No - the filter can still return the undesired value. The localization files are not loaded synchronously, so there is no guarantee that they will be available of a onetime binding is used.

**Comment by lopesc** [comment]
Is there any advantage to using this:
`<span translate = "{{::'KEY'}}"></span>`.  I assume that just the bit inside the double quotes `"{::'KEY'}}"` will be removed from the watcher  (since it is an expression). This will resolve to just `"KEY"`, and the directive itself will still be watching that attribute - Therefore for one to use a bind-once and forget approach, they would be limited to the filter only.

**Comment by lopesc** [comment]
@PascalPrecht @knalli

**Comment by bmhumadi** [comment]
I was able to use one-time binding without any library like bind-once
`<span translate="play"></span> 
`
to 
`<span>{{:: 'play' | translate }}</span>
`

I hope this helps others. It took me hours to find this solution
