### ISSUE TITLE
Add a prefix or nested translation

### ISSUE THREAD

**Issue by xnf** [angular-translate/angular-translate#744]
Hi. Excuse me if this issue was discussed/resolved, but i burn in desperate desire to contribute. 
I use this wonderful module on a kind-of large system with thousands of translation keys and i feel a desperate need for some sort of grouping. 
Currently i prefix keys like SectionA:Button:Save, SectionB:Button:Save, but maybe you have thought about some general approach? For instance - adding a "translate-prefix/section/area" that would find same keys with: 
&lt;ANY translate-prefix="SectionA:" translate&gt;Button:Save&lt;ANY&gt;
&lt;ANY translate-prefix="SectionA:"&gt;{{'Button:Save'|translate}}&lt;/ANY&gt;
&lt;ANY translate-prefix="SectionA:" ng-bind="'Button:Save'|translate"&gt;&lt;/ANY&gt;

or perhaps i would be possible to use an object approach where values are objects like:
{"SectionA":{"Button":{"Save":"Save Section A"}}} and they can be adressed:
&lt;ANY translate&gt;SectionA.Button.Save&lt;/ANY&gt;
&lt;ANY&gt;{{'SectionA.Button.Save'|translate}}&lt;/ANY&gt;
&lt;ANY ng-bind="'SectionA.Button.Save'|translate"&gt;&lt;/ANY&gt;

Perhaps the later approach could go well with #604

**Comment by irnc** [comment]
@knalli Besides the already implemented namespaces, this issue asks about another concept, namely the `translate-prefix` directive.

Consider following markup and the long namespaces used:

```html
<div class="welcome">
  <section id="login">
    <h1 translate>start-page.welcome.login.heading</h1>
    <p translate>start-page.welcome.login.help-text</p>
  </section>
  <section id="sign-up">
    <h1 translate>start-page.welcome.sign-up.heading</h1>
    <p translate>another.namespace.id</p>
  </section>
</div>
```

It would be more convenient to have `translate-prefix` directive at parent element, e.g.

```html
<div class="welcome" translate-prefix="start-page.welcome">
  <section id="login" translate-prefix=".login">
    <h1 translate>.heading</h1>
    <p translate>.help-text</p>
  </section>
  <section id="sign-up" translate-prefix=".sign-up">
    <h1 translate>.heading</h1>
    <p translate>another.namespace.id</p>
  </section>
</div>
```

What do you think about this approach? Would you be willing to see relevant pull request?

**Comment by knalli** [comment]
> What do you think about this approach? Would you be willing to see relevant pull request?

Basically, we like pull requests! :star2: However we probably have to discuss some implementation (proposals), for example performance trade offs or other stuff. That's either part of the PR (could be a WIP!) or as a dedicated proposal / technical discussion.

**Comment by lepipele** [comment]
Can we then start discussion on this? Because I really think this would be welcome addition if it doesn't impact performance too much. It helps a lot with clarity, typing and is natural extension of namespaces - if you are allowing:

	{
		namespace: {
			title: "Title",
			body: "Body"
		}
	}

Then instead of:

	<div>
		<p translate>namespace.title</p>
		<p translate>namespace.body</p>
	</div>

We should be able to support:

	<div translate-ns="namespace">
		<p translate>title</p>
		<p translate>body</p>
	</div>

This is definitely not a critical feature, but it would be nice to have.

**Comment by dietergeerts** [comment]
This would be awesome! We now have modules with each their own translation sets, as our product can enable/disable modules depending on some configuration. So we have to add them to the main angular-translate translation set with some sort of prefix. Because of this, we end up with long keys like MODULE_NAME.GROUP_NAME.LABEL.KEY. So it will definitely improve readability and spare use of such long keys, which now gives us many splitted lines.

**Comment by EdgarsZagorskis** [comment]
First i gave up and started on using namespaces in keys as namespace.subnamespace.key, but it indeed breaks the layout for small elements such as buttons, tabs, menus. So having namespaces as argument would be cool and it would be even compatible with current solution. I hesitate to do that, but since knalli said "we like pull requests", i could give it a go :)

**Comment by lepipele** [comment]
@knalli @tspaeth
Can we get this issue reopened? Or, if there is already another similar issue merged into that?

**Comment by tspaeth** [comment]
maybe #641 ? Dunno.

**Comment by lepipele** [comment]
Yeah - that seems similar enough. So, from what I understand there needs to be technical discussion on how this should be implemented? Or this style is what everybody agrees is the best:

<div translate-ns="namespace">
    <p translate>title</p>
    <p translate>body</p>
</div>

**Comment by tspaeth** [comment]
Basically I guess the question is: are there any volunteering developers making a PR? 
As in my projects, I'm not having the need for such a structure, so someone else should preferably develop such a feature - 
@lepipele are you interesting in making a PR on that thing? 
We'd be happy to have someone helping out here. Any of the participants in this issue or ion #641...?

Otherwise it's just a bit of endless paperwork / discussion on this issue :cry:

**Comment by lepipele** [comment]
@tspaeth you can see from discussion that @irnc and @EdgarsZagorskis expressed willingness to give it a try. @knalli just said: "However we probably have to discuss some implementation (proposals), for example performance trade offs or other stuff."

Doubt that my AngularJs knowledge is good enough for coding this - but I am definitely willing to test. Plus, once branch / repo for this feature is created I can review code and see if there is anything I can help with.

**Comment by lepipele** [comment]
What we can do for now is definitely merge all these discussions in one, keep it open and start getting more people involved in discussion.

**Comment by irnc** [comment]
I will give it a try. But do not expect PR sooner than mid-April I guess due to taught work schedule.
