### ISSUE TITLE
Prevent localStorage locale from overriding $translate.use(fallbackLocale)

### ISSUE THREAD

**Issue by Francisc** [angular-translate/angular-translate#764]
Hello,

I save the last used locale in localStorage and set set the fallback language to be English.
Both in the config phase of the app.

The issue occurs when, in the run phase, I read a URL query param and call `$translate.use('en')`, the same locale as the fallback locale.

What happens is the locale saved and retrieved from localStorage wins. This only happens when trying to switch to the fallback language (English). Any other languages do switch and update the localStorage value.

English is already loaded and cached as it's the fallback language.
When `$translate.use` is called, it does what it's supposed to immediately because of the file being cashed.

This is what I suspect happens:
Right after that, the language that was in localStorage finishes loading and calls `$translate.use` again, but now with the locale which was set before switching to English. This overrides the localStorage value and sets it to be the current locale. Thus, the fallback language never gets to be set.

Any clues without a code example? :)

**Comment by knalli** [comment]
We have actually covered these cases https://github.com/angular-translate/angular-translate/blob/a2ac7000f94bcee6dd8e206cab5d7cec3527dd25/test/unit/service/translate.spec.js#L423-L600 -- an outdated request will not being used as "new". However, because everything is asynchronous, the result of a translation request could be different (i.e. due fallback logic).

**Comment by knalli** [comment]
Closed due inactivity.
