### ISSUE TITLE
recommend use angular $cacheFactory notation for useStorage method

### ISSUE THREAD

**Issue by delagen** [angular-translate/angular-translate#772]
Currently

```
$translateProvider.useStorage("translateStorage");
```

use notation of 

```
{
        set: function (name, value) {
        },
        get: function (name) {
        }
}
```

but common $cacheFactory use

```
{
        put: function (name, value) {
        },
        get: function (name) {
        }
}
```

so need to change `set` to `put` method to simplify use of other storage engines without wrappers.

**Comment by tclift** [comment]
FYI this is a breaking change for anyone implementing a custom storage provider. Due to [this guard](https://github.com/angular-translate/angular-translate/commit/ef6a613e70c0e2fcf2c32fe4b0ad1ffa51be4f0c#diff-255d6d49cbc024fa0d5bc97fdd721bf4R980) the custom storage service must implement `put`.

The commit comments suggest that this wouldn't be the case until 3.0, and the docs still refer to `set` only.

Perhaps the guard should be for `get && (put || set)`?

**Comment by knalli** [comment]
Which docs refer to `set`?

**Comment by tclift** [comment]
@knalli [The Guide, Custom Storages chapter](http://angular-translate.github.io/docs/#/guide/11_custom-storages)

**Comment by knalli** [comment]
Ah, I see. It will be refreshed on next release.

Already covered in #867.

**Comment by tclift** [comment]
OK. So it was intended to be breaking for 2.5, not 3.0?

**Comment by knalli** [comment]
No.. we've actually not considered existing providers.
