### ISSUE TITLE
Update docs to more accurately reflect links behaviour & links feature suggestion

### ISSUE THREAD

**Issue by adrianduke** [angular-translate/angular-translate#805]
So I got very confused when I started trying to use the following in my translations, and found the links weren't being resolved:

``` javascript
{
  GENERIC: {
    LET_US_KNOW: 'Please let us know if you come across this issue.'
  },
  TRUSTPAY: {
    FRIENDLY_RESPONSE_CODES: {
      COMMUNICATION_BREAKDOWN: "There was a problem in communications between us and our provider, it appears they didn't understand us.",
      1004: "@:TRUSTPAY.FRIENDLY_RESPONSE_CODES.COMMUNICATION_BREAKDOWN @:GENERIC.LET_US_KNOW"
    }
  }
}
```

and my output was as follows:

``` html
<p>TRUSTPAY.FRIENDLY_RESPONSE_CODES.COMMUNICATION_BREAKDOWN @:GENERIC.LET_US_KNOW</p>
```

It appears you can only have one link inside a value and it must be the only thing to appear in that value (e.g. `"@:GENERIC.LET_US_KNOW"`), so the following doesn't work either (which I also was confused by):

``` javascript
{
  GENERIC: {
    LET_US_KNOW: 'Please let us know if you come across this issue.'
  },
  TRUSTPAY: {
    FRIENDLY_RESPONSE_CODES: {
      1004: "There was a problem in communications between us and our provider, it appears they didn't understand us. @:GENERIC.LET_US_KNOW"
    }
  }
}
```

I think it would be great to update the docs on this matter so someone in the future doesn't get stuck like I did. I read about the feature in: http://angular-translate.github.io/docs/#/guide/02_getting-started

---

More interestingly though would be to include my expected behaviour as a feature, as it would reduce the word count in translations and allow for a bit more flexibility. Obviously the developer could get themselves in an infinite loop (key referencing another key that references original key), but I would think thats a worthwhile trade off for reducing the amount of text required.

As far as I can tell you can currently get this behaviour using interpolation, but that would be pretty ugly and the async version would be a horrible nested chain:

``` javascript
{
  A: "There was a problem processing your request. {{contact_us}}",
  CONTACT_US: "Please contact us if you have this issue"
}
```

``` javascript
$scope.message =  $translate.instant('A', {contact_us: $translate.instant('CONTACT_US')});

// OR

$translate('A', {contact_us: $translate.instant('CONTACT_US')}).then(function(msg){
  $scope.message = msg
});

// OR

$translate('CONTACT_US').then(function(contactus){
  $translate('A', {contact_us: contactus}).then(function(msg)
    $scope.message = msg
  );
});
```

And I guess you could also fudge it together with multiple translation ID's, but then your moving translation composition into views or controllers which doesn't seem right:

``` javascript
{
  A: "There was a problem processing your request.",
  CONTACT_US: "Please contact us if you have this issue"
}
```

``` javascript
$translate(['A', 'CONTACT_US']).then(function(translations){
  $scope.message = translations.A + " " + translations.CONTACT_US;
});
```

Thanks,
Adrian

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
