### ISSUE TITLE
feat(translate placeholder): support for translating placeholder attribute

### ISSUE THREAD

**Issue by Nate-Wilkins** [angular-translate/angular-translate#874]
It'd be nice if I could translate my placeholders when there's a `translate` attribute on the element that also has a `placeholder` attribute. Maybe even a `translate-placeholder` directive? 

```html
<input type="text" translate placeholder="Enter some text..." />
```

Instead of

```html
<input type="text" ng-attr-placeholder="{{ 'Enter some text...' | translate }}" />
```

This starts to enter some other domains like angular and other libraries but since it is apart of html inputs I feel like we still need to be able to translate those.

**Comment by knalli** [comment]
Are you happy with `translate-attr-placeholder`?

http://plnkr.co/edit/J4Ai71puzOaA0op7kDgo?p=preview

**Comment by Nate-Wilkins** [comment]
@knalli man your fast - my bad 

Thanks!

**Comment by rajush** [comment]
@knalli I'm using `translate-attr-placeholder` with `ng-model` on the input tag
```html
<input placeholder="Regular Placeholder" translate translate-attr-placeholder="text" translate-value-browser="{{app.browser}}" ng-model="inputvalue">
```
and the problem is that the `ng-model` scope value seems to be undefined when tried to access from the controller. 
But when used as a filter `placeholder="{{ 'text' | translate }}"`, it works fine and I can access the `ng-model` scope variable from the controller. 

**Q:** Is there a way that `ng-model` scope value could be accessed while using translate as an attribute instead of a filter?

Any suggestion will be greatly appreciated! Thanks.

**Comment by zycbob** [comment]
@rajush 
`<input placeholder="Regular Placeholder" translate translate-attr-placeholder="text" translate-value-browser="{{app.browser}}" ng-model="$parent.inputvalue">`

**Comment by rajush** [comment]
@zycbob Thank you! 👍

**Comment by brada1703** [comment]
This worked perfectly for the placeholder, but is there a way to do it with the title?

I have tried, 

`title="Regular Title" translate translate-attr-title="RESERVATION_emailaddress" translate-value-browser="{{app.browser}}"`

which didn't work.

Any idea?

Thanks!

**Comment by zycbob** [comment]
@brada1703 As I can see it's working here:
http://plnkr.co/edit/n0FSlJoUlWCXQFEmY5oi?p=preview

**Comment by saeb-panahifar** [comment]
Thanks, It's useful.
