### ISSUE TITLE
Incorrect behavior of multiple $translation.use() calls with asynchronous loading

### ISSUE THREAD

**Issue by jelisejev** [angular-translate/angular-translate#894]
I've stumbled upon this problem when working on a project. I wanted to implement a translation cloak to prevent untranslated text flickering. I did everything but I was supposed to, but the text still flickered. I started debugging and noticed that the problem appeared when $translation.use() was called multiple times. Deeper research of the source code showed that there was some weird logic in $translation.use(). When I first called it, it started an request to load the translation file and saved the promise. On the second call, which occurred before the file was loaded, it checked that it already has a promise and thought, that the file has already been loaded, and it can switch to the new language and fire the $translateChangeEnd event. That, in turn, removed the cloak and caused the flickering. 

I was able to reproduce it with this punkr http://plnkr.co/edit/rUse8rV3Zs9j34EOxHIv

I believe that the second call should do nothing until the promise has been resolved.

**Comment by knalli** [comment]
@jelisejev Using the built-in directive _translate-cloak_, you should have a useful tool for your purpose.

Anyway: Thank you for the hint about the incorrect loading result issues.. this calls are currently needed because it controls fallback languages as well as asynchronous loaded languages. Currently, this guarantees the order of language presence is correct.

So, a simple patch like ```js 
} else if (langPromises[key]) {
  langPromises[key].then(deferred.resolve, deferred.reject);
} else {
```

will not work.

Until someone can improve this without destroying the correct orders of asynchronous language loaders, this work's like expected.
