### ISSUE TITLE
Dynamic adding of partial translation files leads to missing translations

### ISSUE THREAD

**Issue by patrickbr** [angular-translate/angular-translate#903]
Hi there,

we are currently building a large web application handling 4 languages. Language files are split into a number of partials, each corresponding to a different part of the app. If a user switches into one of these parts, a partial file is added via 
```
$translatePartialLoaderProvider.addPart(<thepart>).
```
The expected behaviour would be that angular-translate checks the translation table if the added part is available for the current language, and if not, asynchronously requests it from the server. However, this does not seem to be the case.

Consider the following scenario, the initial language being 'de':
```
$translatePartialLoaderProvider.addPart('main');
$translate.use('fr').then(function() {
    $translatePartialLoaderProvider.addPart('coolpart');
});
```
Everything works as expected, the 'coolpart' language files are loaded because `$translatePartialLoaderStructureChanged` is fired in [line 338](https://github.com/angular-translate/angular-translate/blob/master/src/service/loader-partial.js#L338) and the files are updated.

However, consider now the following (then() flow just used to demonstrate temporal ordering):
```
$translatePartialLoaderProvider.addPart('main');
$translate.use('fr').then(function() {
    // we are now using language FR, that means FR is loaded with part 'main'

    $translate.use('de').then(function() {
        // we are now using language DE again
        $translatePartialLoaderProvider.addPart('coolpart'); // coolpart is loaded for DE

        // [...] (time passes)

        $translate.use('fr').then(function() {
            // back to FR

            // no update is triggered because 'fr' is already present in the translation table
            // => 'coolpart' translation is missing for 'fr'!
        });
    });
});
```

The problem is that for example in [line 1477 of translate.js](https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1477), there is only a check if the language is already present in the translation table - but there is no check if _all parts_ have been loaded for that language. On the other hand, the `$translatePartialLoaderProvider` just handles parts on a global basis - not per language, so `$translatePartialLoaderStructureChanged` is not fired if a part is added that has been previously added in another language.

This lead to difficult to reproduce bugs in our application where whole parts of the website were just filled with blank translation placeholders, but only if you followed a specific 'click path' through the application in different languages

I think that `$translatePartialLoaderProvider` should keep the added parts on a per-language-basis to fix this problem.

We are using version 2.2 in our production environment, but the problem is equally reproducable in 2.5.2

**Comment by DWand** [comment]
Hello, @patrickbr. The `$translate` service knows nothing about parts - it uses translation tables returned by the loader. That's why it uses old translation table when return back to French. To fix this you have to refresh translation tables when you add parts to the loader. This way the `$translate` service will call the loader to update existing translation tables.

**Comment by patrickbr** [comment]
Yes, we are doing it like that at the moment. However, we fear that this can lead to redundant file requests. Does the $partialLoader know about translation files/parts it has already loaded?

**Comment by DWand** [comment]
Yes. It loads only those parts which were not loaded before.
https://github.com/angular-translate/angular-translate/blob/master/src/service/loader-partial.js#L46-L70

**Comment by patrickbr** [comment]
Perfect, then I guess this issue can be considered closed :)

**Comment by Bessonov** [comment]
I run in the same issue. Controllers are lazy loaded and trigger addPart in ui-route resolve to load translations. However, the behavior of angular-translate isn't deterministic. For example in following (stolen) [plunker](http://plnkr.co/edit/rku2Ulqmxv55bcDNg0EE?p=preview), if you click first on Mods and then on French - french language is loaded. But not in other ways.

refresh() is'nt solution, because:
1. This lead to loading much more than needed. The policy of project is to lazy load all what possible: controllers, directives, resources, services, (bigger) templates, translations, css and so on... but:
2. For perfomance and UX reasons translations for fallback/default language delivered through $translateProvider.translations in .config. And because this can't be loaded with partial loader after refresh.

Is there any solution for this or I do something wrong?

**Comment by DWand** [comment]
Hello, @Bessonov. If you use the partial loader, then it is better to use the `$translatePartialLoaderProvider.setPart` method instead of the `$translateProvider.translations`. Providing direct translations to the loader will prevent it from loading them from the server.

**Comment by Bessonov** [comment]
Thank you, @DWand! But it does not help in my setup (it's a little bit complicated to create plunker with all aspects). The problem is similar to #175. See Plunker from [Pascal](http://plnkr.co/edit/CAAdF1?p=preview): replace 'uses' with 'use' in app.js:51 (or use [my fork](http://plnkr.co/edit/hvQ2I1xA5EOXu91Pkzs8?p=preview)) and then click on German, Test, English.
