### ISSUE TITLE
How to translate? Controller vs view? Directive vs Filter?

### ISSUE THREAD

**Issue by rfgamaral** [angular-translate/angular-translate#931]
At work we are having a discussion on the preferred method to translate our strings using `angular-translate`... Should we perform the translations on the controller or view?

If the controller, should we use the `$translate` service or the filter?

If the view, should we use the directive or the filter?

Pros and cons of each method?

Some people argue that it should be in the controller to avoid extra heavy work on the view. Other argue that translations are presentation detail and should be done on the view.

Thoughts?

**Comment by DWand** [comment]
Hello, @rfgamaral.

As for me, translation is a part of the presentation layer. You may use any tool to translate the application, you may even change it or use several tools at once, but it should not affect the business logic. Also, it would be better to keep all translations in one place to make it easier to maintain. That's why I prefer to perform translation in views.

As for the service, directive and filter - it depends on the particular situation. The service fits nicely to controllers and services. Directives and filters are the only fit for views. For regular translations it is better to use directive, while the filter helps a lot is some smaller cases. Here is what the [docs](http://angular-translate.github.io/docs/#/guide/05_using-translate-directive) say about the directive:

> It turned out that having too many filters in a view sets up too many watch expressions, which is why angular-translate also provides a directive to translate your contents in view layer.

IMHO :-)
