### ISSUE TITLE
Update bower requirement of angular v1.2 to 1.3

### ISSUE THREAD

**Issue by tot-ra** [angular-translate/angular-translate#942]

**Comment by knalli** [comment]
What do you mean? https://github.com/angular-translate/bower-angular-translate/blob/2.6.1/bower.json 

1.3 is included?

**Comment by tot-ra** [comment]
How is it different from https://github.com/angular-translate/angular-translate/blob/master/bower.json ?

**Comment by knalli** [comment]
That one (angular-translate) does not define any dependencies for bower.. only in case for development where 1.2 is still in support.

bower-angular-translate contains only the relevant files for you and an appropriate version range.

If you use `bower install angular-translate`, you will get bower-angular-translate.

So again: What do you mean? What is you actual problem? Both 1.2 and 1.3 should work out of the box. 1.3 will be included by default (since 2.6), but 1.2 will work without a warning.

**Comment by tot-ra** [comment]
When doing bower update, i get conflict of angular version. It might be my project ofcourse, but why do angular-translate-cekyy#1.2.0, angular-translate-loader-static-files-ceky#0.1.9 resolve to strict 1.2.0?
![2015-03-03 11 32 04](https://cloud.githubusercontent.com/assets/445122/6459622/003a1a4c-c199-11e4-8b05-71d151d21845.png)

**Comment by knalli** [comment]
1. What is angular-translate-cekyy? Not ours.
2. What is angular-translate-loader-static-files-ceky? Not ours.
3. Said this, both requires an AJS 1.2.
4. Same for angular-file-upload.

So actually everything works as expected from my point of view.

**Comment by tot-ra** [comment]
Ok, thanks, I've uninstalled angular-translate-cekyy and that solved the problem, sorry for your time

**Comment by knalli** [comment]
:star2:  :)
