### ISSUE TITLE
Loaded Static Files undefined error. Plunker not working

### ISSUE THREAD

**Issue by dimitriscsd** [angular-translate/angular-translate#983]
Hello.

I am trying to get a static file example working in my application however I am getting an undefined is not function error when I try to do $translateProvider.uses('en_US');

I am basing everything on your example plunker at http://plnkr.co/edit/Hw4iMz?p=preview which also seems to not be working when I run it.

**Comment by knalli** [comment]
@dimitriscsd In short: you are using an old AngularJS version, and new angular-translate version, and an app.js which is incompatible with angular-translate. The "undefined" was coming from a change of angular-translate 2.0 (!)

In detail:
1. You should not include untagged/unversioned imports/includes in JsFiddle/Plunkrs. rawgithub actually does not like this. Either use rawgit.com production cdn or cdnjs.com instead.
2. Use proper current releases, but at least compatible ones.
3. You should not include minified codes because it is bad to read and understand. Unless it is minified, you are able to read the performed code.

> I am basing everything on *your example plunker* at http://plnkr.co/edit/Hw4iMz?p=preview which also seems to not be working when I run it.

Do we reference to this examples? Could you please tell us where you have find it? We should fix this, because it fools people. :(

**Comment by knalli** [comment]
Updated plunker: http://plnkr.co/edit/RJugnMpptbHCnPjDqVgm?p=preview

**Comment by dimitriscsd** [comment]
Thank you for the immediate response.

Here is where I found the reference for that plunker:
https://github.com/angular-translate/angular-translate/wiki/Asynchronous-loading

**Comment by knalli** [comment]
Oh.. please use angular-translate.github.io and forget everything which is in the Wiki. :|
