### ISSUE TITLE
Translation keys cannot contain interpolatation containers

### ISSUE THREAD

**Issue by worldspawn** [angular-translate/angular-translate#985]
Hey if I have a key like `{{'TEST {{thing}}' | translate }}` it fails with 
![image](https://cloud.githubusercontent.com/assets/819581/6956136/1789c7f2-d935-11e4-964a-02381bac1f1a.png)

Which i get is a function of angular, nothing you can do about it. But the filter could provide an alternative syntax eg: #{thing#} and the filter can find and replace {# with {{ etc before interpolating it.

I dont like to use keys eg HOME_TEXT instead preferring to use english as the key. So I need to able to use the filter like `{{'Hello, {{firstName}}' | translate }}`

I can write my own filter easily enough but perhaps your library could consider this scenario?

```
$provide.decorator('translateFilter', function ($translate) {
        var translateFilter = function (translationId, interpolateParams) {
          translationId = translationId.replace('#{', '{{').replace('}#', '}}');

          return $translate.instant(translationId, interpolateParams, undefined);
        };

        return translateFilter;
      });
```

`{{'TEST #{loginModel.username}#' | translate:this }}`

**Comment by knalli** [comment]
@worldspawn Well, sounds interesting. 

A contribution would be fine, but I would suggest making the `#` configurable. More or less the same as AJS internal optional override feature for starting and ending expression tags.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?
