### ISSUE TITLE
Directive should prefer "translate" attribute's value over element text

### ISSUE THREAD

**Issue by tiblu** [angular-translate/angular-translate#986]
**Code**
`
  <pre translate="TRANSLATION_ID">This is the default</pre>
`

http://plnkr.co/edit/ZGqE7guPegfzEZ6YdJ6a?p=preview

**Result**

Translate "evaluation" order:
- "This is the default"
- "TRANSLATION_ID"

**Proposed**

Proposed "evaluation" order:
- "TRANSLATION_ID"
- "This is the default"

**Problem**

When using `angular-translate-handler-log` despite the fact that "MY_KEY" exist, warning is logged to "Translation for This is the default doesn't exist".

I find it useful to keep original text in the HTML element, so that template makes more sense when you look at it. I don't want to replace all the default texts with translation keys. It makes it harder to follow the template and merge any changes made by the HTML coders.

Plus the elements contents then acts as "default" text when no translation is found.

And the pure template can be opened and viewed in the browser as-is.

**Comment by knalli** [comment]
Adding an option which do not refresh the directive's text until the translation has been successful (not rejected)? Okay..

However, one note: This also means further translation rejections will result into invalid states. Because no refresh would mean that an already applied translation will be not overridden (but is wrong). And even if there would be define an additional condition (like only on initial time = first success) the intended behavior would not be possible after the next language change.

I think that's okay, but it should be at least noteable.

**Comment by darrylkuhn** [comment]
I wanted this too so I took a stab at it. You can see it here https://github.com/angular-translate/angular-translate/compare/master...aristamd:master and for those that just want to bring it into their project a complied / minified version is available here: https://github.com/aristamd/bower-angular-translate. 

Not sure all the implications of these changes since I'm new to the project. I changed a few of the test cases since the expected behavior had changed but otherwise all tests pass. Would love to merge this in to origin if suitable. Cheers!

**Comment by soluml** [comment]
+1 ... I'm currently seeing the `TRANSLATION_ID` or a brief second before the translated text comes through. It's very noticeable on slower connections. Would love to default it to something else or hide the text entirely while it waits for the translation.

**Comment by knalli** [comment]
@soluml it looks like a regular issue about FOUC which is handled in the guide. And this issue is not handling that kind of situation.

**Comment by soluml** [comment]
Sorry, it sounded very similar to this issue. I've tried translate-cloak and it doesn't solve the issue. If I had the default text showing instead of the variable ID, it would look nicer.  I'll keep looking around the docs, thanks!

**Comment by darrylkuhn** [comment]
Anything I can do to support the review process?

**Comment by knalli** [comment]
Still an issue?

**Comment by tiblu** [comment]
Looks good to me! (http://plnkr.co/edit/fTDtCfq6c95J1H1EEp1m?p=preview)
Thanks for all the work @darrylkuhn @knalli
